### ISSUE TITLE
Are ENT functions school specific?

### ISSUE THREAD

**Issue by bain3** [bain3/pronotepy#100]
A few of our ENT functions ([ac_grenoble](https://github.com/bain3/pronotepy/blob/1d65fa07d87872e2be9ce043508d8a957cdfe375/pronotepy/ent.py#L41), [atrium_sud](https://github.com/bain3/pronotepy/blob/1d65fa07d87872e2be9ce043508d8a957cdfe375/pronotepy/ent.py#L148) for example) have a specific school address in some of their requests. Is this ok? Do they work with other schools?

**Comment by OiseauDesPlages** [comment]
I don't really understand, why wouldn't they work well with others?

**Comment by Bapt5** [comment]
@bain3 no it will not work with other schools. I had already noticed the problem but forgot to report it.

**Comment by bain3** [comment]
> I don't really understand, why wouldn't they work well with others?

Because sometimes they have a specific hard-coded "service" (like atrium sud: `?service=https:%2F%2F0060013G.index-education.net%2Fpronote%2F`) which points to a specific school. I guess we need to pass the school url to the function and make this variable?

**Comment by Bapt5** [comment]
@bain3 Not sure but maybe it can work without this url param. Because I would be surprised if the site gives the cookies according to the param.

**Comment by bain3** [comment]
We'd need to test it. Honestly I wouldn't be surprised... All of this authentication stuff is super sketchy.

**Comment by MRakox** [comment]
I use the atrium-sud ENT with another Pronote URL than the one hard-coded [here](https://github.com/bain3/pronotepy/blob/1d65fa07d87872e2be9ce043508d8a957cdfe375/pronotepy/ent.py#L148) and it works without any problem.
