### ISSUE TITLE
Login through QR codes

### ISSUE THREAD

**Issue by bain3** [bain3/pronotepy#101]
JsonLines has done excellent work and reverse engineered QR code authentication. This is a great way to bypass ENTs. 
https://github.com/Androz2091/pronote-qrcode-api

If we implement this, we should release it in v3.0.0, since we will probably have to break our current Client creation system.

**Comment by Bapt5** [comment]
@bain3 If you want, I can try to implement that. I think we can keep the old login system. And user will choose which system they use.

**Comment by bain3** [comment]
Yup, we're keeping the old system for sure but for people with ENTs this could be waay easier. You can try and implement it if you want. Should I assign you to this?

Technical note: This would probably mean that we would split logging in and initialising the client. Maybe have two functions `login` for normal login and `login_qr` for qr login.

**Comment by Bapt5** [comment]
Yes, good idea, I had thought of exactly that. You can assign this to me, but I'll probably need some help as it's a big job.
