### ISSUE TITLE
Add ent77.seine-et-marne.fr

### ISSUE THREAD

**Issue by theCrazylegs** [bain3/pronotepy#103]
Hello 
Thanks for your work, is it possible to add ent77.seine-et-marne.fr ?

I have not the login and password to access directly to pronote, I only access with this URL : https://ent77.seine-et-marne.fr

Direct Access Pronote => https://0772589w.index-education.net/pronote/parent.html
Redirect => https://ent77.seine-et-marne.fr/auth/login?callback=%2Fcas%2Flogin%3Fservice%3Dhttps%253A%252F%252F0772589W.index-education.net%252Fpronote%252Fparent.html#/

Thanks for your help
Best

**Comment by Bapt5** [comment]
Hi
Ent 77 works like the ent_essonne.  Maybe you can try to implement it on your own.  Otherwise I will do it next week.
