### ISSUE TITLE
ENT  monbureaunumerique

### ISSUE THREAD

**Issue by fbarth75** [bain3/pronotepy#110]
It doesn't work , but when i take alook at the code i think i find the error here :
 # ENT / PRONOTE required URLs
    ent_login_page = "https://cas.monbureaunumerique.fr/login?selection=EDU&service=http%3A%2F%2Fpronote.lycee-fabert.com%2Fpronote%2F&submit=Valider"
    ent_load = "https://educonnect.education.gouv.fr/idp/profile/SAML2/POST/SSO"
    ent_login = "https://educonnect.education.gouv.fr/idp/profile/SAML2/POST/SSO?execution=e1s1"
    pronote_verif = "https://cas.monbureaunumerique.fr/saml/SAMLAssertionConsumer"

Ent_login_page is not for my school , do i need to change it from my login url ?

https://cas.monbureaunumerique.fr/login?service=https%3A%2F%2Fclg-jamyn.monbureaunumerique.fr%2Fsg.do%3FPROC%3DPAGE_ACCUEIL

**Comment by Bapt5** [comment]
This issue was fixed in #109
