### ISSUE TITLE
KeyError: 'moyEleve' for class Period.averages(), pronotepy.exceptions.ParsingError: Error while parsing received json

### ISSUE THREAD

**Issue by TheGeeKing** [bain3/pronotepy#112]
File "C:\Users\polic\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\dataClasses.py", line 263, in averages
    return [Average(c) for c in crs]
  File "C:\Users\polic\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\dataClasses.py", line 263, in <listcomp>
    return [Average(c) for c in crs]
  File "C:\Users\polic\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\dataClasses.py", line 354, in __init__
    self.student: str = self._resolver(Util.grade_parse, "moyEleve", "V")
  File "C:\Users\polic\AppData\Local\Programs\Python\Python39\lib\site-packages\pronotepy\dataClasses.py", line 135, in __call__
    raise ParsingError("Error while parsing received json", self.json_dict, path)
pronotepy.exceptions.ParsingError: Error while parsing received json

**Comment by bain3** [comment]
I see. This should probably be optional.

**Comment by bain3** [comment]
By the way this doesn't look like a pronotepy's problem but that the pronote doesn't give averages? Correct me if it does... I think in this case it would be best to raise a different some kind of `UnsupportedOperation` error...

**Comment by TheGeeKing** [comment]
> By the way this doesn't look like a pronotepy's problem but that the pronote doesn't give averages? Correct me if it does... I think in this case it would be best to raise a different some kind of `UnsupportedOperation` error...

Updated, forgot a part of the traceback.
So issue is that schools can completely disable access to all averages and so the code try to access something that isn't in the dict. Would be cool if pronotepy goes in manual mode and get grades and calculate the averages manually, and same for #111.

**Comment by bain3** [comment]
That's a little iffy. I'd even say to rip out the manual overall average functionality. Pronotepy is here to give you access to the pronote API, not to calculate stuff for you. :thinking: We should do one thing right not multiple barely. Implementing this feature yourself from `Period.grades` is not hard.

**Comment by TheGeeKing** [comment]
If Period.grades works in the first place haha

**Comment by bain3** [comment]
Should not be fixed lmao

**Comment by TheGeeKing** [comment]
Easy fix. Thanks
