### ISSUE TITLE
Does new workflows automatically check and correct files?

### ISSUE THREAD

**Issue by TheGeeKing** [bain3/pronotepy#115]
I know that there are automatisation that can apply black and mypy to committed files automatically when you do a PR. Question is: does it do it or does it have to be done anyway? @bain3

**Comment by bain3** [comment]
Currently they only check if they are correctly formatted and run. You still need to run them on your machine to correct the code.

**Comment by TheGeeKing** [comment]
Could be nice:
black: https://github.com/psf/black/actions/runs/17913292/workflow
mypy: https://github.com/tsuyoshicho/action-mypy

**Comment by bain3** [comment]
Looks like we can't do black :(
https://github.com/cclauss/autoblack#tldr-it-does-not-work

**Comment by TheGeeKing** [comment]
💀🔫
