### ISSUE TITLE
Attachements (links) of homework?

### ISSUE THREAD

**Issue by nouni19** [bain3/pronotepy#119]
Hello, I'm wondering if there's a way to check links in homework

**Comment by Bapt5** [comment]
Helle I don't understand the question. Can you give an example please?

**Comment by nouni19** [comment]
For example, if the teacher wanted to show us a video, she would include it as a link

**Comment by nouni19** [comment]
And then it would show up in the list of resources (Dernieres resources pedagogiques)

**Comment by Bapt5** [comment]
Okay I understand I will implement that.

**Comment by Bapt5** [comment]
Links are in the files method of homework.
