### ISSUE TITLE
Latest version installation error

### ISSUE THREAD

**Issue by nouni19** [bain3/pronotepy#121]
Hello, because of the newest addition (files), I needed the latest version. So I took the command from the README, and I got an error:

"ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output"
"UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 8: character maps to <undefined>"
And that error is in appdata\local\programs\python\python39\lib\encodings\cp1252.py

**Comment by bain3** [comment]
Hmm I'm not sure what's happening here but it doesn't look like a problem on pronotepy's end though. This file is not in pronotepy's source.

**Comment by bain3** [comment]
You can try and clone the repository and then run `pip install .` but other than that I don't think we can help.
