### ISSUE TITLE
Problème de connexion 

### ISSUE THREAD

**Issue by FireFull45** [bain3/pronotepy#125]
Bonjour,
je suis bloqué avec cette erreur, quelqu'un peut-il m'aider ?

Traceback (most recent call last):
  File "c:\Users\FireFull\Desktop\Pronote\pronotePy\QCM.py", line 11, in <module>
    client = pronotepy.Client('https://0450051l.index-education.net/pronote/eleve.html?login=true',
  File "C:\Users\FireFull\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\clients.py", line 290, in __init__
    super().__init__(pronote_url, username, password, ent)
  File "C:\Users\FireFull\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\clients.py", line 51, in __init__
    cookies = ent(username, password)
  File "C:\Users\FireFull\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\ent\cas_edu.py", line 99, in ac_orleans_tours
    return cas_edu('https://ent.netocentre.fr/cas/login?&idpId=parentEleveEN-IdP', username, password)
  File "C:\Users\FireFull\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\ent\cas_edu.py", line 27, in cas_edu
    "RelayState": soup.find("input", {"name": "RelayState"})["value"],
TypeError: 'NoneType' object is not subscriptable

---

Voici le programme utilisé :

```
import pronotepy
from pronotepy.ent import ac_orleans_tours
client = pronotepy.Client('https://0450051l.index-education.net/pronote/eleve.html?login=true',
                          username='****',
                          password='*****',
                          ent=ac_orleans_tours)
if client.logged_in:
    periods = client.periods
    for period in periods:
        for grade in period.grades:  
            print(f'{grade.grade}/{grade.out_of}')  
```
Merci

**Comment by Bapt5** [comment]
@FireFull45 Please try this code
```python
import pronotepy
from pronotepy.ent import ac_orleans_tours
client = pronotepy.Client('https://0450051l.index-education.net/pronote/eleve.html',
                          username='****',
                          password='*****',
                          ent=ac_orleans_tours)
if client.logged_in:
    periods = client.periods
    for period in periods:
        for grade in period.grades:  
            print(f'{grade.grade}/{grade.out_of}')  
```
You mustn't put ?login=true at the end of the url if you want to connect with your ENT.

**Comment by FireFull45** [comment]
I removed the ?login=true but the problem is still the same :/

```
import pronotepy
from pronotepy.ent import ac_orleans_tours

# creating the client and passing the occitanie_montpellier function to automatically get cookies from ENT
client = pronotepy.Client('https://0450051l.index-education.net/pronote/eleve.html',
                          username='****',
                          password='****',
                          ent=ac_orleans_tours)
# check if sucessfully logged in
if client.logged_in:
    periods = client.periods
    for period in periods:
        for grade in period.grades:  
            print(f'{grade.grade}/{grade.out_of}')  

```

**Comment by Bapt5** [comment]
@FireFull45 I fix the problem on my repo. 
If you want to install now the fix version execute this command `pip install git+https://github.com/Bapt5/pronotepy.git`
Otherwise wait for my next pull request
