### ISSUE TITLE
bug sur pornote .py

### ISSUE THREAD

**Issue by titof2375** [bain3/pronotepy#131]
Bonjour, je réouvre ce poste car ca ne fonctionne plus chez moi , je suis sur ent creuse et je suis compaitement perdu la , jai vue juste au dessi pip install lxml et quand je veut l'installée je me retrouve avec plein d'erreur.
![dsqsdsqdsqds](https://user-images.githubusercontent.com/31250165/163809335-754e7de4-15bd-4444-a5df-1872b496c9a9.PNG)

**Comment by titof2375** [comment]
![vvfgfvdfd](https://user-images.githubusercontent.com/31250165/163809809-9ddebc89-7e72-4082-badb-2d383db431d3.PNG)

**Comment by Bapt5** [comment]
Bonjour @titof2375 je ne comprend pas ce que vous voulez. Vous mettez une erreur comme ça. Je ne sais même pas ce que vous avez exécuté.

**Comment by titof2375** [comment]
salut escuse moi , j'ai un peut du mal a m'explique a tu discord ou telegram?

**Comment by Bapt5** [comment]
Vas y envoie ton discord @titof2375

**Comment by titof2375** [comment]
titof2375#6264
