### ISSUE TITLE
ENTLoginError : Failed to connect with EduConnect (ent2d_bordeaux)

### ISSUE THREAD

**Issue by KeyKatyu** [bain3/pronotepy#134]
Hi,

I'm writing this issue because I would like to use your library but I can't because I'm not able to import the academy of bordeaux's ent.
When I write "from pronotepy.ent import ent2d_bordeaux" it doesn't work.
How I can do that ?

Thanks.

**Comment by Bapt5** [comment]
Hi @KeyKatyu It's not enough to import the function for your ent but also need to use it. Try this script by replacing with your login credentials. 
```python
import pronotepy
from pronotepy.ent import ent2d_bordeaux

client = pronotepy.Client('https://0000000a.index-education.net/pronote/eleve.html',
                          username='demonstration',
                          password='pronotevs',
                          ent=ent2d_bordeaux)
# check if sucessfully logged in
if client.logged_in:
    print(len(client.messages())) # printing number of messages that the user has
else:
    print('no login')
```

**Comment by KeyKatyu** [comment]
Yes I know, but this import doesn't exist.
When I use it like your script, I got this error : 

> Traceback (most recent call last):
>   File "c:/Users/xxxxxx/Desktop/test/program.py", line 3, in <module>
>     from pronotepy.ent import ent2d_bordeaux
> ImportError: cannot import name 'ent2d_bordeaux' from 'pronotepy.ent' (C:\Users\xxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pronotepy\ent\__init__.py)

**Comment by Bapt5** [comment]
@KeyKatyu You probably didn't t install the library. Please execute `pip install https://github.com/bain3/pronotepy/archive/refs/heads/master.zip`

**Comment by KeyKatyu** [comment]
I have already installed the library correctly. It works with the others ENTs. I just think that **ent2d_bordeaux** has been forgotten in PronotePy.

**Comment by Bapt5** [comment]
No I tell you that he has not been forgotten. The proof in the attached photo
![IMG_20220502_195249](https://user-images.githubusercontent.com/63651713/166299252-485e5ae2-f315-4ebc-94a3-a05c2f341fe7.jpg)

**Comment by Bapt5** [comment]
@KeyKatyu I think you haven't the last version of pronotepy. So please execute `pip install https://github.com/bain3/pronotepy/archive/refs/heads/master.zip`

**Comment by KeyKatyu** [comment]
I'm French, I saw you're French too, we can speak french if you want.
Thank you for taking the time to help me.

I just uninstalled the PronotePy and reinstalled it with your command (PIP). Do you confirm that it is version 2.4.0?

I checked afterwards, Python keeps telling me that this import does not exist in the terminal (look at the screenshot below). Does ``ent2d_bordeaux`` work for you? This is all very strange...
![image_2022-05-02_205945391](https://user-images.githubusercontent.com/67519620/166308399-de5b3ff9-4cb9-45d6-b484-75ee51133a43.png)
![Sans titre](https://user-images.githubusercontent.com/67519620/166309307-c422653e-a818-47a2-b23b-0eb29a2bf0a2.png)

**Comment by Bapt5** [comment]
It works for me. @KeyKatyu So please execute 
```console
pip uninstall pronotepy
pip install https://github.com/bain3/pronotepy/archive/refs/heads/master.zip
```

**Comment by KeyKatyu** [comment]
I just ran these commands, no changes.
``ent2d_bordeaux`` is still missing from ``pronotepy.ent``.

**Comment by KeyKatyu** [comment]
EDIT : I tried on a VM and it works, idk why. :)

But know, I get this error : 
``pronotepy.exceptions.ENTLoginError: Fail to connect with EduConnect : probably wrong login information``

(I'm sure I put the correct login information)

**Comment by Bapt5** [comment]
@KeyKatyu For this error excuse me, it was my fault. I fix the problem. To install the last version execute `pip install git+https://github.com/Bapt5/pronotepy.git`

**Comment by KeyKatyu** [comment]
It works, thanks you !
