### ISSUE TITLE
Timetable

### ISSUE THREAD

**Issue by gaufriti** [bain3/pronotepy#135]
Hello I searched in the doc but I want to be certain, can't we see our timetable with this api ?

**Comment by bain3** [comment]
Hi, yes you can using [pronotepy.Client.lessons](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.clients.html#pronotepy.clients.Client.lessons).

**Comment by gaufriti** [comment]
oh yes sorry i'm blind ig
