### ISSUE TITLE
Photo de profil

### ISSUE THREAD

**Issue by jusdecitron** [bain3/pronotepy#136]
Bonjour,
Je souhaite savoir s'il est possible de récupérer notre photo de profil dans Pronote et de l'afficher d'une manière ou d'une autre.

Cordialement.
Citron.

**Comment by Bapt5** [comment]
Just use `client.info.profile_picture` in the latest version

**Comment by jusdecitron** [comment]
Merci beaucoup !
________________________________
De : Baptiste D ***@***.***>
Envoyé : dimanche 15 mai 2022 22:15
À : bain3/pronotepy ***@***.***>
Cc : Citron ***@***.***>; Author ***@***.***>
Objet : Re: [bain3/pronotepy] Photo de profil (Issue #136)


Just use client.info.profile_picture in the latest version

**Comment by jusdecitron** [comment]
Bonjour, désolé

**Comment by Bapt5** [comment]
`pip install -U git+https://github.com/bain3/pronotepy` execute this command please

**Comment by Bapt5** [comment]
@jusdecitron Can you close this issue please if it is solved.
