### ISSUE TITLE
Useing 'parent' url with mutliple kids in the same school: only shows one kid

### ISSUE THREAD

**Issue by vingerha** [bain3/pronotepy#137]
I received a request for my wrapper from a parent who wants to use his parent access to get data from both kids being on the same (!) school.
However, when using that, only one is shown and not sure why only this one (possibly the first one entering the school)
The documentation does not show any info on this so asking if you would know how.

The workaround would be using the individual access for each of the kids, but the question here is to use the parent access only.

**Comment by Bapt5** [comment]
Hi @vingerha You can use the method [pronotepy.clients.ParentClient.set_child](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.clients.html#pronotepy.clients.ParentClient.set_child) to set the child you want to focus on. You cannot indeed get the data for all the children at the same time, but you can get them for each child by set again the child.

**Comment by vingerha** [comment]
Thanks, seems to be working and now need to find out how to interactively arrange for this....it is fun to write wrappers but the exceptions drive me mad :)

**Comment by Bapt5** [comment]
@vingerha If i have answered all your questions please close the issue

**Comment by vingerha** [comment]
One questoin before I do this, is there also somehting as a 'get_child' ? I would like to prevent hardcoding hte uernames in the call, so if I could do a get_child and get 1,2,3.. etc. responses than I could iterate over that

**Comment by Bapt5** [comment]
There is no method for that, but I can try to implement this. I will keep you informed.

**Comment by vingerha** [comment]
Thanks, for the time being I will go for hardocded and assume max 2 children... really appreciating the fast response

**Comment by bain3** [comment]
Hi, PronoteClient has a children attribute, so you can view all `children` the account has access to with that. There is also a `_selected_child` attribute. It is private. I guess we could make it public. You can still use it though.

**Comment by Bapt5** [comment]
It's true sorry I had forgotten the existence of this attribute

**Comment by vingerha** [comment]
Got it...thanks
```
clist = client.children
for x in clist:
    print (x.name)
