### ISSUE TITLE
url attribute of File objects are not correctly generated!

### ISSUE THREAD

**Issue by DodoLeDev** [bain3/pronotepy#138]
Hi!
While I was using pronotepy for a new project, each time I wanted to download a file, I have encountered this error:
```
FileNotFoundError: The file was not found on pronote. The url may be badly formed.
```
After multiple checks, I noticed that generated links are incorrect!
I think there is a problem between lines 519 and 528 of the [dataClasses.py](https://github.com/bain3/pronotepy/blob/master/pronotepy/dataClasses.py#L519) file:
```py
        padd = Padding.pad(
            json.dumps({"N": self.id, "G": 1}).replace(" ", "").encode(), 16
        )
        magic_stuff = client.communication.encryption.aes_encrypt(padd).hex()

        self.url = (
            f"{client.communication.root_site}/FichiersExternes/{magic_stuff}/"
            + quote(self.name, safe="~()*!.'")
            + f"?Session={client.attributes['h']}"
        )
```
Maybe the *magic stuff* needs to be updated?

**Comment by Bapt5** [comment]
Yes, the problem is already known but thanks for bringing it up. I'm currently working on it
