### ISSUE TITLE
Notes coefficients

### ISSUE THREAD

**Issue by firmin-launay** [bain3/pronotepy#14]
Hello,
Using the library, I enountered a problem: coefficients that are not integers don't display correctly. I had a quick look at the code and found the line responsible for that:
```Python
"coefficient": ("coefficient", int),
```
(_dataClasses.py    line 268_)

You just have to make the coefficient a string instead of an integer to fix the problem. That would be great if it was modified in the next releases.
Thanks.

**Comment by bain3** [comment]
Hello,
thank you for notifying me. I applied the fix you suggested.
