### ISSUE TITLE
More options for grades

### ISSUE THREAD

**Issue by TKiller1** [bain3/pronotepy#140]
Hello,
Is it possible to add boolean attributes to the Grade object, to indicate if the grade is calculated out of 20 and if the test is optional? I could not find such attributes in the documentation.
Examples:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/90258360/172159457-9b4e11c8-c2da-449e-943e-249338bcbcad.png">
<img width="289" alt="image" src="https://user-images.githubusercontent.com/90258360/172159503-366f4a5e-45e5-4a67-8092-256f9f80f52e.png">

**Comment by Bapt5** [comment]
Hello
There is no need to add a boolean attribute to indicate if the grade is calculated out of 20 because there is already an `out_of` attribute. So you can test yourself if the grade is calculated out of 20. 
But I will add a boolean attribute to indicate if the test is optional.

**Comment by TKiller1** [comment]
Thanks a lot!

**Comment by TKiller1** [comment]
Hello,
I think that the "grade calculated out of 20" option is different from simply getting the out_of attribute. I checked the out_of attribute of the grade in my example, and I found that it was 7. I think this option has to do with the calculation of the average of a subject for my school's Pronote. Here is the calculation of the average of the subject from my example:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/90258360/172385283-2c13d6f2-3763-424c-8f3b-656d327b7ac0.png">

**Comment by Bapt5** [comment]
OK I will try to see what a I can do

**Comment by TKiller1** [comment]
Thank you very much, your contributions are what inspire me to code.

**Comment by Bapt5** [comment]
@TKiller1 Done. I added 
* is_bonus : bool : is the grade bonus : only points above 10 count
* is_optionnal : bool : is the grade optionnal : the grade only counts if it increases the average
* is_out_of_20 : bool : is the grade out of 20. Example 8/10 -> 16/20

Execute `pip install git+https://github.com/Bapt5/pronotepy` to install my changes
