### ISSUE TITLE
New ent

### ISSUE THREAD

**Issue by Sami6053** [bain3/pronotepy#144]
Hello,
can you add this ent ?
ac_nantes

thanks

**Comment by Bapt5** [comment]
Can you give me more infos : the URL of the ENT for example?

**Comment by Bapt5** [comment]
@Sami6053 I think that the high schools of the academy of Nantes use ENT elyco.  The `ent_elyco` function already exists for this ENT.

**Comment by Sami6053** [comment]
yes, it's elyco.
what can i white in my py for ent_elyco?
please

**Comment by Bapt5** [comment]
Yes and then you initialize the client with the function ent_elyco. But can you give me the URL of your ENT anyway?

**Comment by Sami6053** [comment]
url: https://sevigne.lamayenne.e-lyco.fr

i've test and now my ip si blocked. i'm waiting and i test later.
thanks for your help
