### ISSUE TITLE
Please create ENT access for Hauts de France

### ISSUE THREAD

**Issue by Holborn13200** [bain3/pronotepy#149]
Hi, please can you create a ENT Access for Hauts-de-France.
What is the url needed?
I have this url: https://enthdf.fr/
Do not hesitate if you need more informations.
Thanks.

**Comment by Bapt5** [comment]
Already done ! please use
```python
import pronotepy
from pronotepy.ent import ent_hdf 

# creating the client and passing the occitanie_montpellier function to automatically get cookies from ENT
client = pronotepy.Client('https://0000000a.index-education.net/pronote/eleve.html',
                          username='your username',
                          password='your password',
                          ent=ent_hdf )
# check if sucessfully logged in
if client.logged_in:
    print(len(client.discussions())) # printing number of messages that the user has
else:
    print('no login')
```

**Comment by Holborn13200** [comment]
So fast, great job! I think it work but i have a problem. 
Visibly for Hauts-de-France the connection to the ENT of my daughter's college is only possible via Educonnect ..
I don't have ENT Login .. 
I tring with temporary password and return this log :

```
DEBUG:pronotepy.ent.generic_func:[ENT https://enthdf.fr] Logging in with B148905BC906
DEBUG:pronotepy.ent.generic_func:[EduConnect https://educonnect.education.gouv.fr/idp/profile/SAML2/Unsolicited/SSO?execution=e1s1] Logging in with B148905BC906
DEBUG:pronotepy.ent.generic_func:Fail to connect with EduConnect, trying with Open NG
DEBUG:pronotepy.ent.generic_func:[ENT https://enthdf.fr/auth/login] Logging in with B148905BC906
```
Do you think a solution exists?
https://educonnect.education.gouv.fr/
Thanks for your job :)

**Comment by Bapt5** [comment]
I had already implanted it a long time ago.  Feel free to look at the documentation.  It already works with Educonnect.

**Comment by Holborn13200** [comment]
Hi and tanks lot for your help.
I tried with different url and I'm sure my login data is correct but impossible to connect..
The Pronote URL Link: https://0595596m.index-education.net/pronote/eleve.html?login=true
I tried without "?login=true" but doesn't work.

issue: Fail to connect with Open NG https://enthdf.fr/auth/login : probably wrong login information
Thanks.

**Comment by Bapt5** [comment]
I just fixed the problem, it was just that Educonnect change something in its authentification.

**Comment by Holborn13200** [comment]
Hi Bapt5 and very good job.
Work fine with my child login but not with my personal login (parent).

I think the problem comes from a double access account (Elementary School and middle School) on the same page like capture bellow. What do you think ?

![Capture d’écran 2022-09-05 à 20 54 45](https://user-images.githubusercontent.com/57837326/188503012-fab9f359-8c45-4e37-99e8-c91e3c416a4e.jpg)

**Comment by Bapt5** [comment]
I don't have access to this choice. I think it will be complicated for me to implement this

**Comment by Holborn13200** [comment]
Too bad, without the parent profile the management of absences is impossible...
What information would you need?
Thanks.

**Comment by Bapt5** [comment]
I think this fonctionnality is to specific. I will not have the time to implement it.

**Comment by Holborn13200** [comment]
Having several children and some in primary school and others in college is far too specific ... Indeed .. Thank you as well and thank you for your work.

**Comment by Bapt5** [comment]
You have misunderstood me. I was saying that I think your ENT is the only one to have this child choice, that's why I was saying that it was specific. I don't have the time to implement the feature but if you want you can try to implement it.
