### ISSUE TITLE
can't connect on my pronote

### ISSUE THREAD

**Issue by starnakin** [bain3/pronotepy#15]
my pronote use an ENT authentification and my pronote login page redirected to the ENT login page.
My login url https://0922397f.index-education.net/pronote/eleve.html

**Comment by Xiloe** [comment]
Hello, have you tried the ENT list available in pronotepy ?

**Comment by starnakin** [comment]
Where is this list ?

**Comment by bain3** [comment]
You can see all the supported ENTs [here](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.ent/). We currently support:

- AC Reims
- AC Reunion
- Atrium Sud
- Occitanie Montpellier

Is your ENT by any chance supported already?

**Comment by Xiloe** [comment]
Fixed in [6aba1a581367d31b7a4ada8acb70ef41abc7e11c](https://github.com/bain3/pronotepy/commit/6aba1a581367d31b7a4ada8acb70ef41abc7e11c)
