### ISSUE TITLE
Module crypto

### ISSUE THREAD

**Issue by LawlietRen** [bain3/pronotepy#157]
ModuleNotFoundError: No module named 'Crypto'

**Comment by bain3** [comment]
Hi, did you install pronotepy correctly? Run `pip install -U pronotepy` to install the latest stable release.

**Comment by LawlietRen** [comment]
@bain3 Hey, everything is up to date but it doesn't work, i also tried to install pycrypto, to remove it and reinstall it, etc but nothing works

**Comment by bain3** [comment]
The crypto module is from our `pycryptodome` dependency. Make sure that it's installed. I'm sorry but this is an environment issue, that is kinda hard to debug like this and is out of scope. It looks like the `pip` command installs the dependency somewhere else and python can't find it. :/

**Comment by vingerha** [comment]
Input, I have this working fine with my main OS and container, both on ubuntu 22.04
I tried two methods
- full pronotepy install 
- a step-wise adding of packages, i.e. adding Crypto, BT4 via pip ... and pronotepy only (!) as folder
