### ISSUE TITLE
Add data from PagePresence / listeSanctionUtilisateur

### ISSUE THREAD

**Issue by bdbogjoe** [bain3/pronotepy#158]
[here](https://github.com/bain3/pronotepy/blob/master/pronotepy/dataClasses.py#L370)  you get absence, can you please add listeSanctionUtilisateur ?

**Comment by bdbogjoe** [comment]
we can use https://github.com/bdbogjoe/pronote-api/blob/master/src/fetch/pronote/absences.js#L125 to know the payload content

**Comment by bain3** [comment]
Hi, this is a little weird, because on the demo site, the retenue is given in the `listeAbsences` list. The `G` attribute of punishments is 41 apparently (at least for detentions). We could create another dataclass for it and parse according to the object's `G` type. We could either then return a `List[Union[Absence, Punishment]]`, or we can create a seperate property that will return just `Punishment`s to keep them separated, which is probably a better idea in terms of usability.

I can get it done this evening.

**Comment by bdbogjoe** [comment]
yes i think better to have dedicated Punishments object, even if we have to query 2 times the same data

**Comment by bain3** [comment]
Could you please download the latest version with `pip install git+https://github.com/bain3/pronotepy.git`, and test if it works? Sometimes the demo website differs from actual PRONOTEs. You can for example run the unit tests with `python -m pronotepy.test_pronotepy`.

**Comment by bdbogjoe** [comment]
yes need to wait a little bit to test :)

**Comment by vingerha** [comment]
Tried it, did the pip install and script.... error
```
 for punishment in period.punishments:
AttributeError: 'Period' object has no attribute 'punishments'
```

**Comment by bain3** [comment]
Thank you @ioull ! I've fixed the parsing for your case.

**Comment by bdbogjoe** [comment]
thanks works fine

**Comment by vingerha** [comment]
Trying with 2.7.0 and fix of bapt5 for agora06
```
Traceback (most recent call last):
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 195, in __call__
    json_value = json_value[p]
KeyError: 'estAvecARParent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/3692670A6ACD9016/docker/homeassistant1/python_scripts/pronote_old_attempts/test.py", line 35, in <module>
    for punishment in period.punishments:
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 402, in punishments
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 402, in <listcomp>
    return [Punishment(self._client, a) for a in absences if a["G"] == 41]
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 1854, in __init__
    self.requires_parent: str = self._resolver(
  File "/home/arjan/.local/lib/python3.10/site-packages/pronotepy/dataClasses.py", line 205, in __call__
    raise ParsingError("Could not follow path", self.json_dict, path)
pronotepy.exceptions.ParsingError: Could not follow path
