### ISSUE TITLE
Stubs are not provided

### ISSUE THREAD

**Issue by Sigmanificient** [bain3/pronotepy#161]
Hi, it sees that your package does not have stubs with typing and mypy support.

It would be really nice to provide a typing package along for people using thoses tools in order to avoid people to generate it by themselves.
Thanks

**Comment by bain3** [comment]
I have added a py.typed marker. Please install the latest version using `pip install git+https://github.com/bain3/pronotepy.git`. Unfortunately we cannot make a stable release right now.
