### ISSUE TITLE
How to retrieve the timetable (emploi du temps)?

### ISSUE THREAD

**Issue by wsw70** [bain3/pronotepy#162]
First of all: **THANK YOU**. It is a real shame we need to go though loops in order to get data from Pronote which is bought with our taxes. </end_rand>

My promote does not expose the iCal feature (I asked the school but I have limited hope, to say the least). I will therefore need to scrape the actual timetable in order to build an iCal and expose it to be used by a digital calendar.

What would be the best approach to address this? I can try to add the functionality but I would appreciate very much some bootstrapping information to avoid reverse-engineering the whole algo.

**Comment by bain3** [comment]
I'm glad you like the library. Pronote's api is horrendous. You can get lessons from a client using the [`Client.lessons`](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.clients.html#pronotepy.clients.Client.lessons) method. This will return a list of lessons from the given time period. Initialisation of the client is documented [here](https://pronotepy.readthedocs.io/en/stable/quickstart.html#client-initialisation).

**Comment by wsw70** [comment]
Thank you for the super fast answer. I thought that `lesson` was for the content but you put everything :)

Do you accept PRs for user-contributed scripts? I plan to build a simple webservice to expose an iCal  version of the data so that it is easy to add the timetable to a digital agenda

**Comment by Bapt5** [comment]
We accept PR. However, we will not include your webservice in pronotepy. Indeed it has no link with the library itself

**Comment by Bapt5** [comment]
@wsw70 Don't know if you know [PronoteBot](https://github.com/Bapt5/PronoteBot) which do what you want to do and which use pronotepy.

**Comment by wsw70** [comment]
> However, we will not include your webservice in pronotepy. Indeed it has no link with the library itself

This was not my intent. I was rather thinking about a wiki section for "user contributions" or "user scripts" so that people can add what they wrote with pronotepy in case it could help someone.

These scripts are obviously not part of the library so they indeed have no place in the code itself.

**Comment by wsw70** [comment]
> if you know [PronoteBot](https://github.com/Bapt5/PronoteBot)

I did not. I will give it a try, thanks!

**Comment by Bapt5** [comment]
Github automatically integrates projects that use Pronotepy in the Used by section of the repo
