### ISSUE TITLE
Couldn't use ENT Occitanie Educonnect

### ISSUE THREAD

**Issue by Starmania** [bain3/pronotepy#164]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/bain3/pronotepy/issues/164)

Hey,
I can't connect to my ENT through the API... It seems that when python tries to get the rsa keys, at `get_response`, the url remains that of my ent...

The variable `get_response.url` is set to `https://cas.mon-ent-occitanie.fr/login?service=https:%2F%2F0300026R.index-education.net%2Fpronote%2Feleve.html`

I tried with two accounts, same problem...

And I can share with you my account

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars.githubusercontent.com/u/47037724?v=4' alt='dathosim' width=24 height=24> dathosim](https://issuehunt.io/u/dathosim) ($2.00)

### Submitted pull Requests
- [#173 Added the service in the url, close #164](https://issuehunt.io/r/bain3/pronotepy/pull/173)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/bain3/pronotepy/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by BloomyInDev** [comment]
Same Problem when you send some request to Pronote URL it"s give that error
(my username and password are not shown)
```
Traceback (most recent call last):
  File "d:\Dev\Python\PronoteStats\main.py", line 4, in <module>
    client = pronotepy.Client("https://0340059e.index-education.net/pronote/eleve.html",username="*******",password:"***********",ent=occitanie_montpellier_educonnect)
  File "C:\Users\L****\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\clients.py", line 382, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "C:\Users\L****\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\clients.py", line 81, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "C:\Users\L****\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\pronoteAPI.py", line 77, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "C:\Users\L****\AppData\Local\Programs\Python\Python310\lib\site-packages\pronotepy\pronoteAPI.py", line 274, in _parse_html
    raise PronoteAPIError(
pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```
