### ISSUE TITLE
Str Object is not callable in pronotepy.Client

### ISSUE THREAD

**Issue by Didoub74-Off** [bain3/pronotepy#171]
Hello, I'm getting this error:
`Traceback (most recent call last):
  File "main.py", line 16, in <module>
    client = pronotepy.Client(pronote_url1,
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/clients.py", line 382, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "/home/runner/Pronote-Note-Mailer/venv/lib/python3.8/site-packages/pronotepy/clients.py", line 70, in __init__
    cookies = ent(username, password)
TypeError: 'str' object is not callable`

The problem is with this line:
```
    ent = os.environ['ent']
    password = os.environ['password']
    username = os.environ['username']
    pronote_url = os.environ['url']

    client = pronotepy.Client(pronote_url=ent,
                            username=username,
                            password=password,
                            ent=ent)
```
Can you help me because, I tried many things and didn't find anything.

**Comment by bain3** [comment]
Hi, the `ent` attribute must be a function that returns cookies ([docs](https://pronotepy.readthedocs.io/en/latest/api/ent.html)). You are currently passing in a `str`.
