### ISSUE TITLE
How to get the attachment(s) of an Information

### ISSUE THREAD

**Issue by amiguet** [bain3/pronotepy#179]
When getting a list of `Infomation` objects with a code along the lines of

```python
client = pronotepy.ParentClient(...)
objs = client.information_and_surveys()
```

I can easily get the title, content, etc. of each obj in objs, but I cannot find a way to get the attachments of the information.

It seems pronotepy can handle Attachments: https://pronotepy.readthedocs.io/en/stable/api/data.html#pronotepy.Attachment

But I don't know how to access them...

Am I missing something? is this even possible?

**Comment by bain3** [comment]
Hi,
I've added [`Information.attachments`](https://pronotepy.readthedocs.io/en/latest/api/data.html#pronotepy.Information.attachments). Let me know if it works :)

**Comment by amiguet** [comment]
Wow, that was quick!

Seems to work perfectly, thanks! :-)
