### ISSUE TITLE
Missing attribute in docs

### ISSUE THREAD

**Issue by firmin-launay** [bain3/pronotepy#18]
Hello,
I just wanted to notify you that an attribute for the dataclass `grade` is missing [here](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.dataClasses/#pronotepy.dataClasses.Grade) in the docs.
Indeed, the attribute `comment` is not listed.
That would be nice if it was added, to provide everyone a complete documentation.
Thanks in advance.

**Comment by Xiloe** [comment]
Hello, thanks for reporting this to us, I am going to fix it soon even though you could do a PR and we would be happy to check and merge it!

**Comment by Xiloe** [comment]
Fixed in [3bf1af7dbae5d1ff0d8d57531da9e8fdf840df5c](https://github.com/bain3/pronotepy/commit/3bf1af7dbae5d1ff0d8d57531da9e8fdf840df5c)

It is actually on the "latest master" docs, not the latest "release one". Will be automatically be on latest release when a release will be pushed.
