### ISSUE TITLE
Add ent toutatice

### ISSUE THREAD

**Issue by fichusalon** [bain3/pronotepy#181]
Bonjour,

Pouvez vous ajouter l'ent de toutatice.fr ?
L'identification se fait via educonnect à cette adresse https://educonnect.education.gouv.fr/idp/profile/SAML2/Redirect/SSO?execution=e1s1

S'il faut des infos supplémentaires n'hésitez pas à me les demander

**Comment by Bapt5** [comment]
C'est déjà fait la fonction a mettre en paramètre est `ac_rennes`. N'hésitez pas à regarder la documentation la prochaine fois avant de créer une issue.

**Comment by fichusalon** [comment]
Bonjour,

J'avais pourtant regardé, sans doute pas assez bien. désolé pour le derangement.

Bonne journée.
