### ISSUE TITLE
connect pronote to notion

### ISSUE THREAD

**Issue by pgtjean** [bain3/pronotepy#186]
Hey, sorry to bother you. I would like to connect pronote to Notion but I can't use your API. Python doesn't show me a module error.
Then I would like to synchronize the calendars, notes, work to be done... on notion. Do you have any ideas to help me?

**Comment by Bapt5** [comment]
Hey Do not hesitate to look at the [documentation ](https://pronotepy.readthedocs.io/en/stable)to set up your link between Pronote and Notion
