### ISSUE TITLE
Loading page before the pronote page ( pronoteAPI.py  ... onload = parsed.find(id="id_body"))

### ISSUE THREAD

**Issue by colseb** [bain3/pronotepy#194]
Hello,

Can you help me, I have the following problem when connecting and parsing the page : 
https://xxxx.index-education.net/pronote/eleve.html ( pronoteAPI.py  ... onload = parsed.find(id="id_body"))

because I have a loading page..

`<html><head><script type="text/javascript"><!--\nfunction leastFactor(n) {\n if (isNaN(n) || !isFinite(n)) return NaN;\n if (typeof phantom !== \'undefined\') return \'phantom\';\n if (typeof module !== \'undefined\' && module.exports) return \'node\';\n if (n==0) return 0;\n if (n%1 || n*n<2) return 1;\n if (n%2==0) return 2;\n if (n%3==0) return 3;\n if (n%5==0) return 5;\n var m=Math.sqrt(n);\n for (var i=7;i<=m;i+=30) {\n  if (n%i==0)      return i;\n  if (n%(i+4)==0)  return i+4;\n  if (n%(i+6)==0)  return i+6;\n  if (n%(i+10)==0) return i+10;\n  if (n%(i+12)==0) return i+12;\n  if (n%(i+16)==0) return i+16;\n  if (n%(i+22)==0) return i+22;\n  if (n%(i+24)==0) return i+24;\n }\n return n;\n}\nfunction go() {\n var p=2611764263735; var s=1077848568; var n;\nif ((s >> 1) & 1) p+=/*\n*13;\n*/795968247*\n2;\telse /*\nelse p-=\n*/p-=198057312*/*\np+= */2;/*\np+= */if ((s >> 2) & 1)/*\nelse p-=\n*/p+=/*\nelse p-=\n*/77276906* 5;/*\n*13;\n*/else /* 120886108*\n*/p-=\n612031117* 3;\tif ((s >> 13) & 1)/* 120886108*\n*/p+=/* 120886108*\n*/69033707*/* 120886108*\n*/14;/*\n*13;\n*/else /*\nelse p-=\n*/p-=/*\n*13;\n*/44992034*\t14;/*\nelse p-=\n*/if ((s >> 6) & 1)p+=/*\nelse p-=\n*/1061267*/*\np+= */9;/* 120886108*\n*/else /*\nelse p-=\n*/p-=/*\nelse p-=\n*/94695195*7;/*\np+= */if ((s >> 3) & 1)p+=/*\n*13;\n*/152873041*4;\nelse /*\np+= */p-=/*\np+= */330571935*\n4;/*\nelse p-=\n*/ p-=548966096;\n n=leastFactor(p);\n{ document.cookie="KEY="+n+"*"+p/n+":"+s+":2067316723:1;path=/;";\n  document.location.reload(true); }\n}\n//--></script></head>\n<body onload="go()">\nLoading...\n</body>\n</html>\n`

do you have a way to wait for the next page for parsing the pronote page?

Thanks for your help

**Comment by bain3** [comment]
Hi,
are you sure you are not using an ENT to connect? Afaik this is not something that PRONOTE would do. Looks like it's trying to rate limit connections by having you do some kind of proof of work. Do the numbers change? I mean they should, but if they don't, then its just a matter of adding a pre-calculated cookie to the session.

**Comment by bain3** [comment]
Else we could make a custom ENT function that calculates the result dynamically.

**Comment by colseb** [comment]
Thank you for your answer.  Yes, I connect with an ENT that of Val_doise, ok I will look for the cookie.  but it will be cool for function

**Comment by bain3** [comment]
The cookie it is setting is called `KEY`. Does it change?

**Comment by colseb** [comment]
yes , the value change :  
document.cookie="KEY="+n+"*"+p/n+":"+s+":2067316723:1;
call next :
document.cookie="KEY="+n+"*"+p/n+":"+s+":4280023100:1;

**Comment by bain3** [comment]
Is it possible to send another HTML of the loading page? I am trying to write a function that generates the cookie, and right now it seems that I'd have to run the script / transpile it to python, and then evaluate it.

The whole thing looks quite home-made, so I wouldn't be surprised if parts of the code stayed static. That would make my job a hell of a lot easier.

**Comment by colseb** [comment]
yes,

<html><head><script type="text/javascript"></script></head>\n<body onload="go()">\nLoading...\n</body>\n</html>

**Comment by bain3** [comment]
Hi, I think the following code should work. I tested it with both HTMLs, and got the correct cookie computed.

<details>
<summary>
long piece of code
</summary>

```py
import requests
from requests.sessions import RequestsCookieJar
import pronotepy
from pronotepy.ent import val_doise
import re
from typing import List

url = "https://xxxxx.index-education.net/pronote/eleve.html"

FUNCTION_BODY_RE = re.compile(r"function go\(\) *\{([\s\S]+)\}")
NUMBERS_RE = re.compile(r"[\d]+")
COMMENTS_RE = re.compile(r"\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$")
SPECIAL_RE = re.compile(r"p *([-+])= *([\d]+);")


def go_func_impl(all_ints: List[int], special: int) -> str:
    """
    Implementation of the go() function without the hard-coded numbers.
    Returns the computed cookie string.
    """
    i = iter(all_ints)
    p = next(i)
    s = next(i)

    for _ in range(5):
        a, b, c, d, e, f = next(i), next(i), next(i), next(i), next(i), next(i)
        if (s >> a) & b:
            p += c * d
        else:
            p -= e * f

    next(i)  # throw away the badly parsed special sub / add
    p += special

    # find smallest factor of p
    n = 2
    if p % 1 or p * p < 2:
        n = 1
    else:
        while n * n < p:
            if p % n == 0:
                break
            n += 1

    return f"{n}*{int(p/n)}:{s}:{next(i)}:{next(i)}"


def custom_ent(username: str, password: str) -> RequestsCookieJar:
    cookies: RequestsCookieJar = val_doise(username, password)

    headers = {
        "connection": "keep-alive",
        "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0",
    }

    loading_page = requests.get(url, cookies=cookies, headers=headers).text

    go_func = FUNCTION_BODY_RE.search(loading_page)
    if go_func is None:
        raise ValueError("failed to find the go() function in the loading page")
    go_func_body = go_func.groups()[0]
    go_func_body = re.sub(COMMENTS_RE, "", go_func_body)

    all_ints = [int(i) for i in NUMBERS_RE.findall(go_func_body)]
    special = SPECIAL_RE.search(go_func_body)
    if special is None:
        raise ValueError(
            "failed to find the special subtraction or addition inside go()"
        )
    sign, num = special.groups()
    special = -int(num) if sign == "-" else int(num)
    cookies["KEY"] = go_func_impl(all_ints, special)

    return cookies


# initialising the client
client = pronotepy.Client(
    url,
    username="demonstration",
    password="pronotevs",
    ent=custom_ent,
)
```

</details>

It tries to log in with the `val_doise` ENT, then it requests the loading page, and parses the HTML for the `go()` function body. Then to compute the cookie it extracts all the numbers from the source code so they can be used in `go_func_impl`.

It is really finicky, but without writing a complete parser for JS, or just using Node externally (which would have its own difficulties), we can't do much better I'm afraid.

**Comment by colseb** [comment]
Thank you very much,  the code works
:)
