### ISSUE TITLE
Debug 

### ISSUE THREAD

**Issue by Err0r-v2** [bain3/pronotepy#203]
How to disable debug like 
`DEBUG:pronotepy.pronoteAPI:[_Communication.post] decryption change
DEBUG:pronotepy.pronoteAPI:indentification
DEBUG:pronotepy.pronoteAPI:{'nom': 'Identification', 'session': 5176223, 'numeroOrdre': '52AC8844E637D39E93EC294292820C4F', 'donneesSec': {'donnees': {'alea': '{7F788073-5664-A0BE-EBE1-2A22ACDB1E06}', 'modeCompMdp': 0, 'modeCompLog': 1, 'challenge': 'F54BE589A6A2F500D4562BA4851FB3A9F6ECFC9F40D4FEE43B2CA3E934C2B25F88849EC9F1B3E3D69A8C00A00BC2C24E'}, 'nom': 'Identification'}}
INFO:pronotepy.pronoteAPI:successfully logged in as spaquin`

**Comment by Err0r-v2** [comment]
Nevermind i just had to put :
`import logging
logging.disable(logging.CRITICAL)`

**Comment by bain3** [comment]
This will set the logging level to `ERROR` only for pronotepy.
```py
logging.getLogger("pronotepy").setLevel(logging.ERROR)
```
