### ISSUE TITLE
Ajout ent LFITokyo

### ISSUE THREAD

**Issue by laurentserena** [bain3/pronotepy#206]
Bonjour<

est ce qu il serait possible d ajouter
https://pronote.lfitokyo.org/parent.html

s il vous plait?

**Comment by Bapt5** [comment]
Bonjour je fais ça prochainement

**Comment by Bapt5** [comment]
Bonjour je viens de vérifier ce n'est pas une ENT. Il vous suffit de vous connecter comme ça : 
```python
client = pronotepy.ParentClient('https://pronote.lfitokyo.org/parent.html',
                          username='votre identifiant',
                          password='votre mot de passe')
```
