### ISSUE TITLE
Fail to connect with CAS

### ISSUE THREAD

**Issue by nic-Oban** [bain3/pronotepy#207]
Hello @bain3,
I recently tried to use pronotepy to get the timetable as my boy want to build a calendar with his friends to check whether they can eat together or not.
Everything is working fine with the demo example (https://github.com/bain3/pronotepy#usage) and he's able to parse the information he needs.
Unfortunately, when he tries to identify himself with ENT (https://github.com/bain3/pronotepy#ent), we have errors : 

`Traceback (most recent call last):
  File "C:\Users\XXX\Downloads\pronote_edt.py", line 18, in <module>
    client = pronotepy.Client('https://0341794r.index-education.net/pronote/eleve.html',
  File "C:\Donnees\Développement_info\Pronote\lib\site-packages\pronotepy\clients.py", line 352, in __init__
    super().__init__(pronote_url, username, password, ent, qr_code)
  File "C:\Donnees\Développement_info\Pronote\lib\site-packages\pronotepy\clients.py", line 64, in __init__
    cookies = ent(username, password)
  File "C:\Donnees\Développement_info\Pronote\lib\site-packages\pronotepy\ent\generic_func.py", line 172, in _cas
    raise ENTLoginError(
pronotepy.exceptions.ENTLoginError: Fail to connect with CAS https://cas.mon-ent-occitanie.fr/login?selection=CSES-ENT_parent_eleve : probably wrong login information
Process finished with exit code 1`

Used code is: 
`client = pronotepy.Client('https://0341794r.index-education.net/pronote/eleve.html',
                         username='n.XXX11',
                         password='MYPSSWD',
                         ent=occitanie_montpellier)
# check if successfully logged in
if client.logged_in:
   print(len(client.discussions())) # printing number of messages that the user has
else:
   print('no login')`

We are in Montpellier, using https://www.mon-ent-occitanie.fr/ and EduConnect to login.

Is there something we are doing wrong?
We'll be happy to help with more information if needed.
Thanks a lot for Pronotepy, my boy is having great time with despite this connection problem!!

Have a good day
Nicolas

**Comment by bain3** [comment]
Hi,
there is a second ENT function for montpellier [`occitanie_montpellier_educonnect`](https://pronotepy.readthedocs.io/en/stable/api/ent.html#pronotepy.ent.occitanie_montpellier_educonnect), maybe try that. Otherwise there is currently an open issue #205, maybe it's the same problem?

> Thanks a lot for Pronotepy, my boy is having great time with despite this connection problem!!

Glad to hear! :)

**Comment by nic-Oban** [comment]
Hey @bain3,
thanks a lot for your superfast answer!
Working fine now ;)
Have a beautiful afternoon!!!
