### ISSUE TITLE
Bot Discord

### ISSUE THREAD

**Issue by Raphiiti** [bain3/pronotepy#214]
Bonjour !

Je voudrais savoir comment utiliser cette api avec un bot discord pour par exemple qu'il nous envoie un message quand on reçoit une nouvelle note.
En attente de votre réponse.
Bonne journée.

Raphiiti

**Comment by Bapt5** [comment]
Bonjour
Vous pouvez lire la documentation https://pronotepy.readthedocs.io/en/stable/
Bonne soirée
