### ISSUE TITLE
Current period is (still) broken

### ISSUE THREAD

**Issue by Poissonardo** [bain3/pronotepy#219]
### **The problem:**

> 
The `pronotepy.Client.current_period` property does not return the proper period when a period is not marked as ended on the server.

### **More detailed explanation:**

While the `pronotepy.Client.current_period` property might work on the demo server provided by index-education which is well configured, in real case situations, periods can be misconfigured by schools and tho a period can have been forgotten to be marked as "ended". This problem is of course not the fault of pronotepy but it can be solved pretty easily in the library.

### **A proposition to solve the problem:**

With the help of the `datetime` library we could check if `datetime.date.today` is included between the start date and the end date of the fetched "current period" from Pronote, if it isn't we could take a slower approach.
We could check if `datetime.date.today` is included between the start and end date of each period, and return the right one.

### **Drawbacks/Conclusion:**

All of this would be a little slower to execute but would avoid a lot of headaches not understanding why does pronotepy don't return the rights elements from `current_period`

**Comment by Bapt5** [comment]
Hi
Pronotepy is a wrapper so it only returns information provided by Pronote.  There is therefore no question of manually calculating the current period.  If you want to find the right period, you can implement this function yourself in your code.

**Comment by bain3** [comment]
Hello, yes I agree with @Bapt5. Just to be sure, the web client also fails to select the current period, right? If not, then I guess we should do something about it.

**Comment by Bapt5** [comment]
Yes for me sometime between two periods the website fail to select the good current period.
