### ISSUE TITLE
Ajouter "toutatice" pour la connexion

### ISSUE THREAD

**Issue by VitriSnake** [bain3/pronotepy#224]
Bonjour,
Serait-il possible d'ajouter une connexion via toutatice ([lien](https://www.toutatice.fr))
Cette ENT utilise EduConnect pour effectuer une connexion,
Merci par avance.

**Comment by Bapt5** [comment]
Bonjour La fonction existe déjà : `ac_rennes`. Merci de regarder la documentation avant de créer une issue !
