### ISSUE TITLE
Error when trying the long term using example in documentaion

### ISSUE THREAD

**Issue by karimk123** [bain3/pronotepy#23]
I copied and pasted this code from the documentation:
            `     import pronotepy
                  import datetime
                  from time import sleep
              
              # initialising the client
              client = pronotepy.Client('https://demo.index-education.net/pronote/eleve.html',
                                        username='demonstration',
                                        password='pronotevs')
              
              # user login check
              if not client.logged_in:
                  print("Client is not logged in")
                  exit()
              
              # getting the initial lesson
              lesson = client.lessons(client.start_day + datetime.timedelta(days=1))[0]
              
              while True: # infinite loop
              
                  # Checks the session status and refreshes the session if it is expired.
                  # Returns True if it has been refreshed.
                  if client.session_check():
              
                      # renew the lesson object
                      lesson = client.lessons(client.start_day + datetime.timedelta(days=1))[0]
              
                      print("Session reinitialised and object renewed.")
              
                  # the content property sends a request to pronote asking for the content (inefficient so don't use it often)
                  print(lesson.content)
                  # lesson.content is pronotepy.LessonContent
              
                  sleep(7200) # wait for 2 hours`

(i replaced the link and password)

When i run this i get this error:
`Traceback (most recent call last):
  File "c:\Users\karim\Documents\Python Projects\Pronotepy\main.py", line 13, in <module>
    lesson = client.lessons(client.start_day + datetime.timedelta(days=1))[0]
  File "C:\Users\karim\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pronotepy\pronoteAPI.py", line 191, in lessons 
    first_week = self.get_week(date_from)
  File "C:\Users\karim\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pronotepy\pronoteAPI.py", line 171, in get_week
    return 1 + int((date - self.start_day.date()).days / 7)
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'`

**Comment by bain3** [comment]
Thank you for notifying me! There was no real reason for `client.start_day` to be `datetime`. You can install the latest version by following the instructions in readme.

**Comment by karimk123** [comment]
Ok thanks!

**Comment by karimk123** [comment]
I updated to the latest version then just tried `print(client.lessons("2021-01-30"))` then i get this error:

`Traceback (most recent call last):
  File "C:\Users\karim\Documents\Python Projects\Pronotepy\main.py", line 13, in <module>
    print(client.lessons("2021-01-30"))
  File "C:\Users\karim\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pronotepy\pronoteAPI.py", line 191, in lessons 
    first_week = self.get_week(date_from)
  File "C:\Users\karim\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pronotepy\pronoteAPI.py", line 171, in get_week
    return 1 + int((date - self.start_day).days / 7)
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.date'`

**Comment by Xiloe** [comment]
It's because of the "-" character between the year/month/day, try using slashes instead.

[or google it. ](https://stackoverflow.com/questions/33194152/unsupported-operand-types-for-str-and-datetime-datetime)

**Comment by karimk123** [comment]
My bad, thanks for helping.
