### ISSUE TITLE
Unité Administrative Immatriculée

### ISSUE THREAD

**Issue by jusdecitron** [bain3/pronotepy#230]
Bonjour,
Je voudrais savoir s'il est possible de récupérer l'UAI (Unité Administrative Immatriculée) d'un établissement à partir de l'API?
J'ai cherché dans `client.func_options` et `client.parametres_utilisateurs` mais il n'y est pas.

J'ai remarqué que la plupart des sites Pronote des établissements commencent par leur UAI puis -index.education.net/pronote 
(sauf pour certains établissements comme celui de LFI Tokyo https://pronote.lfitokyo.org/. Je présume qu'ils possèdent leur propre serveur au lieu que ça soit hébergé par Index-Education).

Quelques infos sur l'UAI:
L'UAI permet d'identifier un établissement en France ou un établissement français à l'étranger.
Il est généralement composé de 7 chiffres et d’une lettre.

**Comment by bain3** [comment]
Hi,
I've found it in the pronote client (application) (Parametres -> Établissement):

![https://bain.cz/t/1cf1cbc84515.png](https://bain.cz/t/1cf1cbc84515.png)

But AFAICT don't think it is sent to the **web** clients. I've tried searching for the string in the FonctionParametres response, and haven't found anything...

**Comment by bain3** [comment]
You could try something like  getting the name of the school using
```py
name = client.func_options["donneesSec"]["donnees"]["General"]["NomEtablissement"]
```
And then querying https://www.education.gouv.fr/acce_public/search.php.

It isn't pretty but could work. You could also try and download the whole list of all schools from the same site. The UI only allows 500 schools per page, but you can send a custom request with a limit closer to 10 000. That successfully divides the whole list into like 8 pages.

**Comment by jusdecitron** [comment]
I tried downloading the whole list with `requests` and `bs4` but I can't seem to get it work.
Can you help me ?

**Comment by bain3** [comment]
You would do something like this:
```py
import requests
import bs4

PAGE_SIZE=10000
amount = 0
total = 1
page = 1

output = {}

while amount < total:
    resp = requests.post(
        "https://www.education.gouv.fr/acce_public/search.php",
        allow_redirects=True,
        data={
            "action": "search",
            "sub_action": "query",
            "page": str(page),
            "sort": "",
            "list_mode": "list",
            "pt_NE_x": "",
            "pt_NE_y": "",
            "pt_SW_x": "",
            "pt_SW_y": "",
            "circle_x": "",
            "circle_y": "",
            "circle_radius": "",
            "layer_mode": "standard",
            "mode": "simple",
            "simple_public": "",
            "localisation": "",
            "facet_group_secteur_public_prive": "on",
            "facet_group_pays": "on",
            "facet_group_region": "on",
            "facet_group_academie": "on",
            "facet_group_departement_insee_3": "on",
            "facet_group_commune_dept": "on",
            "facet_group_etat_etablissement": "on",
            "facet_group_ministere_tutelle": "on",
            "facet_group_nature_uai": "on",
            "facet_group_niveau_uai": "on",
            "facet_group_categorie_juridique": "on",
            "facet_group_categorie_financiere": "on",
            "facet_group_contrat_etablissement": "on",
            "facet_group_situation_comptable": "on",
            "facet_group_specificite_uai_restr": "on",
            "facet_group_type_zone_uai_restr": "on",
            "facet_group_map": "0",
            "text_filter_region": "",
            "page_size": str(PAGE_SIZE),
        }
    )
    soup = bs4.BeautifulSoup(resp.text, features="lxml")

    total = int(soup.find(attrs={"id": "numfound"}).text.replace(" ", ""))

    table = soup.find(attrs={"summary": "Liste des établissements"}).find("tbody")
    sum = 0
    for row in table.find_all("tr"):
        sum += 1
        c = row.find_all("td")
        print("\t".join([i.text for i in c])) # print out the table in tsv format

    amount += sum
    page += 1
```
This prints out the whole list in TSV format. I'm not sure if this will work though... Sometimes the school is just called "Primary school" thus resulting in many duplicates...

**Comment by jusdecitron** [comment]
Salut, je viens de le tester à l'instant. 
J'ai réussi à mettre la liste des établissements sur un tableur Excel, pas de duplicatas selon l'outil "Remove Duplicates" !

Merci infiniment à toi !
