### ISSUE TITLE
get information

### ISSUE THREAD

**Issue by Ymajine** [bain3/pronotepy#231]
salut je n'est pas compris ce que je devais mettre dans le paramètre 'dict' pour recuperer des info
pouvez m'aider ?
info = pronotepy.Information(client=client,json_dict=)

**Comment by bain3** [comment]
You would get new published informations using [`Client.information_and_surveys()`](https://pronotepy.readthedocs.io/en/stable/api/clients.html#pronotepy.Client.information_and_surveys).
