### ISSUE TITLE
What is the date format to Client.homeework(firstdate,seconddate) ?

### ISSUE THREAD

**Issue by Spectralo** [bain3/pronotepy#232]

**Comment by bain3** [comment]
[`Client.homework()`](https://pronotepy.readthedocs.io/en/stable/api/clients.html#pronotepy.Client.homework) accepts `datetime.date` objects, so they do not have to be in a specific format. Please see the [quickstart section](https://pronotepy.readthedocs.io/en/stable/quickstart.html#homework).
