### ISSUE TITLE
Download automatically attached files in homeworks and lessons

### ISSUE THREAD

**Issue by ckarlos22** [bain3/pronotepy#234]
Hi,

Thanks for your work and your development.
I've just discovered pronotepy and I try to download automatically attached files from homeworks and lessons in order to store on a NAS or a cloud.
I do not succeed in doing that.
I'm a litlle bit dummy...

How can I do that ?

My script is something like that:

client = pronotepy.Client(
    "https://demo.index-education.net/pronote/eleve.html", 
    "demonstration", 
    "pronotevs"
)

if client.logged_in: # check if client successfully logged in

    today = datetime.date.today() 
	
    homeworks = client.homework(today) 
    for homework in homeworks: 
		#download attached files

    lessons = client.lessons(today)
    for lesson in lessons:
		#download attached files

Could you help me ? 
Thanks in advance.

**Comment by bain3** [comment]
Hi
you can use the [`files`](https://pronotepy.readthedocs.io/en/stable/api/data.html#pronotepy.Homework.files) property on homework to get the attached files. For lessons you would use [`lesson.content.files`](https://pronotepy.readthedocs.io/en/stable/api/data.html#pronotepy.Lesson.content) to get files attached to a lesson. Beware that `lesson.content` is very inefficient and sends a request out for each lesson content so I wouldn't use it more than necessary.
```py
for homework in client.homework(today, today): # limit to today's homework only
    for file in homework.files:
        file.save(str(homework.date) + file.name)

for lesson in client.lessons(today):
    for file in lesson.content.files:
        file.save(str(lesson.start) + file.name)
```
I didn't test the code but it would be something like this

**Comment by ckarlos22** [comment]
Thanks a lot. Got it !
I think that I struggled because at the date I tried to collect files, there was no file... and I didn't add a test (if) content is not None.
A last question, I try to add the subject (Matiere) in the names of the files to save (before the date).
I use homework.subject but it return something like that <pronotepy.dataClasses.Subject object at 0x7fadb0cc40>
Do you I have an idea idea where i'm going wrong ?

**Comment by bain3** [comment]
`lesson.subject` is indeed a [`Subject`](https://pronotepy.readthedocs.io/en/stable/api/data.html#pronotepy.Subject) instance. To get the subject name: `lesson.subject.name`.
