### ISSUE TITLE
KeyError 'place'

### ISSUE THREAD

**Issue by cbroissa-github** [bain3/pronotepy#239]
Bonjour,
J'ai une erreur depuis quelques jours en lançant le script avec la version à jour de pronotepy.

```
Traceback (most recent call last):
  File "python_scripts/pronote.py", line 79, in <module>
    lessons_today = client.lessons(date.today())
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/clients.py", line 403, in lessons
    output.append(dataClasses.Lesson(self, lesson))
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/dataClasses.py", line 790, in __init__
    - 1
KeyError: 'place'
```

Une idée de correction ?
Merci.

**Comment by bain3** [comment]
Hello,
is it possible that you're fetching a special lesson, or maybe a school event?

I really need more debugging information... Could you maybe run this script, replacing the `date` with the date of the special lesson, and paste the output here? You can remove all the private fields of course, I just need to see the structure.
```py
import pronotepy
import datetime
import json

client = pronotepy.Client(
    "https://demo.index-education.net/pronote/eleve.html",
    username="demonstration",
    password="pronotevs",
)

date = datetime.date(2023, 5, 19)


# patch the __init__ function to catch the KeyError
old_init = pronotepy.dataClasses.Lesson.__init__

def new_init(self, client, json_dict):
    try:
        old_init(self, client, json_dict)
    except Exception as e:
        print(json.dumps(json_dict, indent=2))

        raise e

pronotepy.dataClasses.Lesson.__init__ = new_init

print(len(client.lessons(date)))
```

**Comment by cbroissa-github** [comment]
snif,
I try but I have this message :
File "/usr/local/lib/python3.7/dist-packages/pronotepy/clients.py", line 701, in post
    return self.communication.post(function_name, post_data)
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/pronoteAPI.py", line 191, in post
    pronote_error_msg=r_json["Erreur"]["Titre"],
pronotepy.exceptions.PronoteAPIError: Unknown error from pronote: 5 | Votre adresse IP est provisoirement suspendue !

I don't know why...

**Comment by bain3** [comment]
Ah! I think you're logging in too many times. Wait like like half an hour and it should work.

**Comment by cbroissa-github** [comment]
It's ok now but the print = 8
len is the length of the object
if I print the lesson object, I have someting like : <pronotepy.dataClasses.Lesson object at 0xb5aa4cd8>

**Comment by bain3** [comment]
Hmm, it should've raised an exception...

I need it to crash so I can see the data which made it crash. Make sure you have replaced the login credentials with your own, and `date` with a date on which you experienced the issue, please.

**Comment by cbroissa-github** [comment]
oups sorry, I understand, I tried to correct the script so there was no more error...
With the error 

```
{
  "N": "1175B400019C4B2",
  "estRetenue": true,
  "numeroSemaine": 38,
  "ListeContenus": {
    "_T": 24,
    "V": [
      {
        "L": "Retenue 16h45 - 17h45",
        "estHoraire": true
      }
    ]
  },
  "imgRealise": "Realise",
  "hintRealise": "R\u00e9alis\u00e9e",
  "horsHoraire": true,
  "DateDuCours": {
    "_T": 7,
    "V": "15/05/2023 16:45:00"
  },
  "DateDuCoursFin": {
    "_T": 7,
    "V": "15/05/2023 17:45:00"
  }
}
Traceback (most recent call last):
  File "python_scripts/pronote.py", line 68, in <module>
    for lesson in client.lessons(date):
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/clients.py", line 403, in lessons
    output.append(dataClasses.Lesson(self, lesson))
  File "python_scripts/pronote.py", line 64, in new_init
    raise e
  File "python_scripts/pronote.py", line 61, in new_init
    old_init(self, client, json_dict)
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/dataClasses.py", line 802, in __init__
    - 1
KeyError: 'place'
```

**Comment by bain3** [comment]
Alright, could you please install the dev version like so:
```
pip install -U git+https://github.com/bain3/pronotepy.git
```
and run the script again? It should not crash now.

**Comment by cbroissa-github** [comment]
It's ok now, thanks.
