### ISSUE TITLE
ENT

### ISSUE THREAD

**Issue by 0x454d505459** [bain3/pronotepy#25]
Hi! Is it possible to add a new ENT, we need the ac-orleans-tours's one called called Netocentre
Here's the link you should consider:

- https://lycees.netocentre.fr/portail/f/welcome/normal/render.uP
- https://ent.netocentre.fr/cas/login?service=https://lycees.netocentre.fr/portail/Login&token=TOKEN_THAT_CHANGE
- https://educonnect.education.gouv.fr/idp/profile/SAML2/Redirect/SSO?execution=e1s1

If you need more infos contact me on discord: NameUndefined#5042

Thanks a lot!

**Comment by Xiloe** [comment]
Hey! Looks like it's based on EduConnect (Like Occitanie's ENT).
You could try to use that as a base (see [ent.py#L116](https://github.com/bain3/pronotepy/blob/0509fbd69a4fcc6dcc92a78dc174ec2c00ed7903/pronotepy/ent.py#L116)), and it should (almost) work
