### ISSUE TITLE
New discussion

### ISSUE THREAD

**Issue by quantsulting** [bain3/pronotepy#250]
Hi I'm not able to generate the message content of the new discussion by passing a straightforward string. I manage to get the subject but the field "message" stays empty. 
Moreover I did not manage to have the correct format to pass the recipients' list (do I have to specify the email address or just id, name and _type ?

**Comment by bain3** [comment]
Hi, you should get recipients from [`Client.get_recipients`](https://pronotepy.readthedocs.io/en/stable/api/clients.html#pronotepy.Client.get_recipients). I couldn't recreate your issue with the message content.

```py
import pronotepy
from pronotepy import Util

client = pronotepy.Client(...)

assert client.logged_in

recip = client.get_recipients()
client.new_discussion("New discussion subject", "A message", Util.get(recip, name="Mme BROWN J."))
```
