### ISSUE TITLE
New ENT for Yvelines Colleges

### ISSUE THREAD

**Issue by guillaume042** [bain3/pronotepy#256]
Oze is dead . Say hello to NEO.
Same interface, same pronote access.

URL : https://ent.ecollege78.fr

Available for any questions or tests. 

Guillaume

**Comment by mguyard** [comment]
Bonjour,

J'ai aussi beaucoup d'intérêt pour l'ajout de cet ENT.
Mais malheureusement les check sont en failed pour la PR de @Bapt5 :(

**Comment by mguyard** [comment]
Bonjour,

Aussi interessé. Malheureusement la PR de @Bapt5 n'a pas passé les checks

**Comment by Bapt5** [comment]
Oui c'est normal les ENT sont cassé depuis longtemps. Il faudrait nettoyer un peu tout ça mais je n'ai pas le temps. J'ai mis mon pull request si yen a qui veulent s'occuper de fix les checks

**Comment by mguyard** [comment]
Merci de l'avoir fait. Plus qu'à attendre le merge dans la branche.

**Comment by Bapt5** [comment]
Je pourrais théoriquement merge moi même vu que je suis maintainer du repo. Mais comme les tests ne passe pas j'attends que quelqu'un qui ait du temps répare ces ENT qui ne fonctionne pas avant de merge

**Comment by guillaume042** [comment]
> Je pourrais théoriquement merge moi même vu que je suis maintainer du repo. Mais comme les tests ne passe pas j'attends que quelqu'un qui ait du temps répare ces ENT qui ne fonctionne pas avant de merge

C'est quelle ENT qui ne fonctionne plus ? En fin d'année scolaire cela fonctionnait encore pour ile_de_france. Pas encore pu tester cette année le pronote du lycée est encore fermé.

**Comment by guillaume042** [comment]
J'ai testé en modifiant le code sur mon serveur directement et ecollege78 cela fonctionne.
Merci

**Comment by Bapt5** [comment]
parfait !
