### ISSUE TITLE
Timetable support

### ISSUE THREAD

**Issue by Moreo18** [bain3/pronotepy#26]
Hello,
It would be cool to have timetable support and some function to see like if a teacher is absent etc...
Would be very cool
Have a great day

**Comment by bain3** [comment]
Hello,
this functionality if already implemented. You can get all lessons in a given timespan using [`Client.lessons`](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.pronoteAPI/#pronotepy.pronoteAPI.Client.lessons). This will return a list of [`pronotepy.Lesson`](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.dataClasses/#pronotepy.dataClasses.Lesson). `pronotepy.Lesson` has an attribute called `canceled` or `status`. Which can tell you if the teacher is absent.
