### ISSUE TITLE
ent2d_bordeaux issue (Argos issue?)

### ISSUE THREAD

**Issue by Komas19-new** [bain3/pronotepy#272]
Hello, i get "pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page." when i launch the script, heres the pronote url i put
![image](https://github.com/bain3/pronotepy/assets/82937056/43aaf48b-820b-41ba-9b17-813e59184bd8)

I might have found the issue, in the code, i have found that ent2d_bordeaux is the link https://ent2d.ac-bordeaux.fr/Shibboleth.sso/Login?SAMLDS=1&target=https%3A%2F%2Fent2d.ac-bordeaux.fr%2Fargos%2Fpr%2Findex%2Findex, but when i access it, i have this below 
![image](https://github.com/bain3/pronotepy/assets/82937056/371935f0-6e7c-4c17-9ad0-faf869eefd08)
and in the url, i see "argos", however, argos no longer exists as you can see in the image below
![image](https://github.com/bain3/pronotepy/assets/82937056/e84205f3-8d34-4e7c-8fae-95623b8ae0d0)
the new place is here: https://wayf.gar.education.fr/?service=med, which requires educonnect password

could this be fixed?

**Comment by Nemesis24** [comment]
hello i'm not sure for the link you've done, because there isn't a way for parent account.
I'm in the same case, but i don't know what is the good way to connect...
I've mad an issue [here](https://github.com/delphiki/hass-pronote/issues/31), to be able testing with qrcode.

**Comment by Komas19-new** [comment]
> hello i'm not sure for the link you've done, because there isn't a way for parent account. I'm in the same case, but i don't know what is the good way to connect... I've made an issue [here](https://github.com/delphiki/hass-pronote/issues/31), to be able testing with qrcode.

you can get through it by doing the image below:
![image](https://github.com/bain3/pronotepy/assets/82937056/53cc4d1e-b45b-4143-8055-0200e26cad37)
and then doing this:
![image](https://github.com/bain3/pronotepy/assets/82937056/626148da-552c-439b-8b9d-e6f5a86b1097)

**Comment by Nemesis24** [comment]
ok but  [here](https://0640019d.index-education.net/pronote/) is the same you are redirected on educonnect no ?

**Comment by Komas19-new** [comment]
> ok but [here](https://0640019d.index-education.net/pronote/) is the same you are redirected on educonnect no ?

it redirects to educonnect then instantly on pronote once you log in, which depends if the school uses educonnect for pronote

édugar tho does not contain pronote as of right now

**Comment by tmonjalo** [comment]
It should be solved with PR #296
(it works for me)
