### ISSUE TITLE
issue with ac-bordeaux.fr ENT

### ISSUE THREAD

**Issue by mostardesign** [bain3/pronotepy#280]
Bonjour,
Malgré plein de tentatives, je n'ai pas accés à mon compte ou celui de mon fils. Il me semble ne pas avoir fait d'erreurs pour me logger. Je suis sur l'académie de Bordeaux. Avez-vous rencontrez ce probleme ?

**Comment by Komas19-new** [comment]
https://github.com/bain3/pronotepy/issues/272

**Comment by tmonjalo** [comment]
Oui j'avais le même problème.
Je l'ai résolu avec ces changements : PR #296
