### ISSUE TITLE
Unable to automatically login to Pronote

### ISSUE THREAD

**Issue by BiasedKiwi** [bain3/pronotepy#281]
So I'm trying to set up a program which runs at set intervals each day (with a cron job), however I can't seem to be able to reuse past credentials: I tried to use qr code login but the passwords reset after each login (I did try to login using `client.username` and `client.password`). I tried using `.Client` to login but I get a `PronoteAPIError` when using my regular credentials. Would there be a way to automatically generate new credentials each time I need to login?

**Comment by bain3** [comment]
Hi! Please carefully read the [quickstart](https://pronotepy.readthedocs.io/en/stable/quickstart.html#logging-in-with-qr-code-recommended). You cannot reuse old credentials. PRONOTE generates a new password one after each login.

**Comment by BiasedKiwi** [comment]
But what about automatically generating new ones?

**Comment by bain3** [comment]
The new password is stored in `client.password` after a successful login.

**Comment by BiasedKiwi** [comment]
Alright, it works now. Thank you!
