### ISSUE TITLE
Unable to connect to pronote, please try again later

### ISSUE THREAD

**Issue by algorythmTTV** [bain3/pronotepy#285]
Whenever I try to run my code, it will allways return an error:

```
import pronotepy

client = pronotepy.Client('0911021r.index-education.net/pronote/eleve.html',
                          username='mon login',
                          password='mon mot de passe')

if client.logged_in:
    periods = client.periods

    for period in periods:
        for grade in period.grades:
            print(f'{grade.grade}/{grade.out_of}')
```

My error is:

`Exception has occurred: PronoteAPIError
Unable to connect to pronote, please try again later
  File "...", line 3, in <module>
    client = pronotepy.Client('0911021r.index-education.net/pronote/eleve.html',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pronotepy.exceptions.PronoteAPIError: Unable to connect to pronote, please try again later`

I'm sure that those login infos are good.
Is there something I am doing wrong?
Thanks

**Comment by tarneaux** [comment]
See the example in the [docs](https://pronotepy.readthedocs.io/en/stable/api/ent.html) and replace `ac_reunion` with `ile_de_france`.

**Comment by algorythmTTV** [comment]
Hey, I forgot the https:// , very sory for the inconvenience...
