### ISSUE TITLE
Problem with end of lessons

### ISSUE THREAD

**Issue by Bapt5** [bain3/pronotepy#29]
Hi 
I have a problem with the end date of the lessons: they are never correct. For example a Lesson that lasts 55 minutes, lasts only 30 min with pronotepy. Can someone help me to try fixe this issue?

**Comment by bain3** [comment]
Hello, I've tried to reproduce this issue, but didn't succeed. Pronote doesn't give us the end time of the hour so we have to calculate it. This works fine on the demo account, and I remember it working with my pronote too.

Could you run this bit of code, and paste here the output? It will print the one time frame duration, and just some json to compare it to from pronote. It will also look at some start and ending times.
**Change the credentials to your account** of course. You can also try it with the demo account, but that should work.
```py
import pronotepy
import json
import datetime

client = pronotepy.Client('https://demo.index-education.net/pronote/eleve.html',
                          username='demonstration',
                          password='pronotevs')

if not client.logged_in:
    print("Client is not logged in")
    exit()

print("One hour duration:", client.one_hour_duration)
print("Liste heures:", json.dumps(client.func_options['donneesSec']['donnees']['General']['ListeHeures']))
print("Liste heures:", json.dumps(client.func_options['donneesSec']['donnees']['General']['ListeHeuresFin']))

# gather some lessons, only show their start and end time
lessons = client.lessons(client.start_day+datetime.timedelta(days=4))
for lesson in lessons:
    print("start:", lesson.start, "  end:", lesson.end)
```

**Comment by Bapt5** [comment]
So I have run your test script and it give me this result: 
`One hour duration: 0:18:00
Liste heures: {"_T": 24, "V": [{"G": 0, "L": "08h12"}, {"G": 1, "L": "08h30", "A": false}, {"G": 2, "L": "09h10"}, {"G": 3, "L": "09h30", "A":false}, {"G": 4, "L": "10h20"}, {"G": 5, "L": "10h30", "A": false}, {"G": 6, "L": "11h18"}, {"G": 7, "L": "11h48", "A": false}, {"G": 8, "L":"12h15"}, {"G": 9, "L": "12h45", "A": false}, {"G": 10, "L": "13h20"}, {"G": 11, "L": "13h50", "A": false}, {"G": 12, "L": "14h18"}, {"G": 13,"L": "14h48", "A": false}, {"G": 14, "L": "15h28"}, {"G": 15, "L": "15h58", "A": false}, {"G": 16, "L": "16h26"}, {"G": 17, "L": "16h30", "A":false}, {"G": 18, "L": "17h23"}, {"G": 19, "L": "17h53", "A": false}, {"G": 20, "L": "18h18"}, {"G": 21, "L": "18h48", "A": false}, {"G": 22, "L":"19h15"}]}
Liste heures: {"_T": 24, "V": [{"G": 0, "L": "08h30", "A": false}, {"G": 1, "L": "09h07"}, {"G": 2, "L": "09h30", "A": false}, {"G": 3, "L":"10h05"}, {"G": 4, "L": "10h30", "A": false}, {"G": 5, "L": "11h12"}, {"G": 6, "L": "11h48", "A": false}, {"G": 7, "L": "12h13"}, {"G": 8, "L":"12h45", "A": false}, {"G": 9, "L": "13h10"}, {"G": 10, "L": "13h50", "A": false}, {"G": 11, "L": "14h15"}, {"G": 12, "L": "14h48", "A":false}, {"G": 13, "L": "15h13"}, {"G": 14, "L": "15h58", "A": false}, {"G": 15, "L": "16h23"}, {"G": 16, "L": "16h30", "A": false}, {"G": 17,"L": "17h20"}, {"G": 18, "L": "17h53", "A": false}, {"G": 19, "L": "18h18"}, {"G": 20, "L": "18h48", "A": false}, {"G": 21, "L": "19h15"},{"G": 22, "L": "19h15", "A": false}]}
`

**Comment by bain3** [comment]
I guess I should've seen this coming. As you can see, you have a few hours at the beginning of the day that are shorter than others. Pronotepy only looks at the first hour, and calculates the time from that. That's why it doesn't work all the time. I will look into it, but if you think you could fix it by making it check properly (using the client.func_options data) then go ahead and do a pull request.

**Comment by Bapt5** [comment]
Okay I think that I have not all understand but I think that I don't know how to fix this issue. Just for information all of my lessons last 55 minutes except certain which last 1 hours 53 minutes.

**Comment by bain3** [comment]
Hello, I think I have fixed the issue. Can you please install the latest version with the instructions from our README, and check everything works fine?

**Comment by Bapt5** [comment]
Okey thank you very much it's work !!
