### ISSUE TITLE
Missing some path

### ISSUE THREAD

**Issue by Aldarande** [bain3/pronotepy#298]
Hi,

In the case of homework request, i receive this kind of debug message :
Could not get value for (path: estServiceGroupe), setting to default.

And i have more path missing for lesson request :
DEBUG  : Could not get value for (path: estAnnule), setting to default.
DEBUG  : Could not get value for (path: estSortiePedagogique), setting to default.
DEBUG  : Could not get value for (path: dispenseEleve), setting to default.
DEBUG  : Could not get value for (path: listeVisios,V), setting to default.
DEBUG  : Could not get value for (path: estRetenue), setting to default.
DEBUG  : Could not get value for (path: cahierDeTextes,V,estDevoir), setting to default.
DEBUG  : Could not get value for (path: estServiceGroupe), setting to default.

I hope it should be add to data class

**Comment by bain3** [comment]
Hi, this is correct behaviour. Some fields are not always available on the lesson object received from pronote, so pronotepy is setting a default value instead.

You can raise the log level for the dataClasses module with:
```py
logging.getLogger(pronotepy.dataClasses.__name__).setLevel(logging.INFO)
```

**Comment by Aldarande** [comment]
OK, i understand if every doesn’t the same p1th.

Tanks a lot
