### ISSUE TITLE
retrieve cookies from his ENT

### ISSUE THREAD

**Issue by HevelMc** [bain3/pronotepy#3]
Hi, I would like to use your API but I don't know how to pick up cookies from my ENT ([Atrium-Sud](https://www.atrium-sud.fr)).

I hope you can help me with that. Thank you for your service which looks great.

**Comment by bain3** [comment]
Hello, I'm really sorry but unfortunately ENTs are very specific for each region. The only thing i can do is link to [this code](https://github.com/bain3/pronotepy/blob/18131388c4d4bf0174cd9ef00418fe53e122c33a/pronotepy/pronoteAPI.py#L164) which gets the cookies from the occitanie ENT. @Xiloe did most of the work (if not all) for ENTs, i don't have experience with them.

**Comment by bain3** [comment]
Could you please contact him on discord? Xiloe#3042

**Comment by HevelMc** [comment]
Thank you for your prompt response. I understand the complexities of working with ENTs. 

I will contact him by Discord, thank you very much ^^

**Comment by Xiloe** [comment]
Fixed in commit [9a48ceec2bbdb4f98f3234687565f6a22a32f7a8](https://github.com/bain3/pronotepy/commit/9a48ceec2bbdb4f98f3234687565f6a22a32f7a8)
