### ISSUE TITLE
trying to access paris pronote but getting error

### ISSUE THREAD

**Issue by tarneaux** [bain3/pronotepy#30]
Hi,
Today I tried accessing my student pronote, but got following error:
`%Run pronoteTest.py
Traceback (most recent call last):
  File "/home/pi/desksave/pronoteTest.py", line 8, in <module>
    ent=ile_de_france)
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/pronoteAPI.py", line 71, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/pronoteAPI.py", line 357, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "/usr/local/lib/python3.7/dist-packages/pronotepy/pronoteAPI.py", line 494, in _parse_html
    "Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.")
pronotepy.pronoteAPI.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.`
The code is following:
`import pronotepy
from pronotepy.ent import ile_de_france

# creating the client and passing the occitanie_montpellier function to automatically get cookies from ENT
client = pronotepy.Client('https://0750611g.index-education.net/pronote/eleve.html',
                          username='secret.idunno',
                          password='DontPeek',
                          ent=ile_de_france)
# check if sucessfully logged in
if client.logged_in:
    print(len(client.messages())) # printing number of messages that the user has
else:
    print('no login')`
If I use it normally i login using the paris ENT and then i click on the pronote app.
Help?

**Comment by bain3** [comment]
Hello, we don't support the paris ENT yet. Maybe @Xiloe could take a look?

**Comment by tarneaux** [comment]
I modified the URL from ile_de_france to https://ent.parisclassenumerique.fr/auth/login?callback=https%3A%2F%2Fent.iledefrance.fr%2F and it worked.
Waiting for the new copy-pasted and name-modified function to be implemented.

**Comment by tarneaux** [comment]
(Now added as paris_classe_numerique in the ENTs)
