### ISSUE TITLE
Issue with pip install -U git+https://github.com/bain3/pronotepy

### ISSUE THREAD

**Issue by quantsulting** [bain3/pronotepy#300]
get the error:  Error parsing dependencies of gym: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    opencv-python (>=3.) ; extra == 'all'

**Comment by bain3** [comment]
Hi,
pronotepy does not have opencv-python, or gym in its dependencies. Something else in your setup must be causing the error.
