### ISSUE TITLE
PronoteAPIError: Bad request

### ISSUE THREAD

**Issue by amiguet** [bain3/pronotepy#301]
I'm again encountering troubles when trying to connect.

A simple 
```
client = pronotepy.ParentClient('https://.../parent.html', username='XXX', password='XXX')
```

results in 

```
pronotepy.exceptions.PronoteAPIError: Bad request (http status: 400)
```

It used to work. I still can log in to the website with these credentials using a regular browser.

Freshly installed latest pronotepy (==2.13.0) in a new venv.

Any idea what's happening? I'm not sure where to start to debug the situation...

**Comment by bain3** [comment]
Hi, fixed in c3e7a02. Looks like your PRONOTE instance is a bit defensive.

**Comment by amiguet** [comment]
Wow, incredibly quick answer and fix!

Seems to work perfectly! :-)

Many thanks!

**Comment by bain3** [comment]
Great to hear!
If you ever get blocked, you can change the fake user-agent pronotepy uses like so:
```py
import pronotepy.pronoteAPI
pronotepy.pronoteAPI.HEADERS = { "User-agent": "..." }
```

**Comment by amiguet** [comment]
Yeah, I saw that in the commit message, but thanks for pointing it out! Hopefully I won't need it, but who knows how paranoid they will get eventually?
