### ISSUE TITLE
QRCode login is not working (eduprovence)

### ISSUE THREAD

**Issue by pelrol** [bain3/pronotepy#305]
Hello,

I tried to use the create_login.py utility to get my credentials from QRCode login.
Here is the data I get from the QRCode:
`{"avecPageConnexion":false,"jeton":"xxx","login":"xxx","url":"https://0132565t.index-education.net/pronote/mobile.parent.html"}`

I have this error message:
`  File "C:\Users\pelro\Documents\code\Pronote2Homeassistant\.venv\lib\site-packages\pronotepy\pronoteAPI.py", line 330, in aes_decrypt
    raise CryptoError(
pronotepy.exceptions.CryptoError: ('Decryption failed while trying to un pad. (probably bad decryption key/iv)', 'exception happened during login -> probably the qr code has expired (qr code is valid during 10 minutes)')`

I am sure the QRCode is less than 10 minutes old and that the PIN code is the correct one (tried several times).
As well I am using the latest code from main branch `(pip install -U git+https://github.com/bain3/pronotepy)`

Am I missing something ?
Thanks!

**Comment by pelrol** [comment]
Thanks @SleepInfinity it does work !

**Comment by GaPhi** [comment]
I tried it too to see if there is a chance to solve #302, after a
successful QRCode decode, I get the following error "Can not login with QR
code: invalid confirmation code"

What can be the solution?

Thanks !

**Comment by SleepInfinity** [comment]
> I tried it too to see if there is a chance to solve #302, after a
> successful QRCode decode, I get the following error "Can not login with QR code: 'ressource'"
> 
> What can be the solution?
> 
> Thanks !

Have you tried with the demo account ?

**Comment by GaPhi** [comment]
Can you tell me what the login/passwd it is or, better, how to get a qrcode for it in order to use the same mechanism as the one I try to use?

Thanks
