### ISSUE TITLE
[ENT Support Request] ent77

### ISSUE THREAD

**Issue by yodn** [bain3/pronotepy#307]
Hi,

I think the link has changed because there is no longer a direct link to connect to https://ent.seine-et-marne.fr/

The link in ent.py which is https://ent77.seine-et-marne.fr/auth/login is redirected to https://ent.seine-et-marne.fr/

Thanks for you support.

**Comment by SleepInfinity** [comment]
Try this:
```python
import requests

HEADERS = {
    "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0",
    'referer': 'https://ent.seine-et-marne.fr/',
}

def _open_ent_ng(
    username: str, password: str, url: str = "", **opts: str
) -> requests.cookies.RequestsCookieJar:
    """
    ENT which has an authentication like https://ent.iledefrance.fr/auth/login

    Parameters
    ----------
    username : str
        username
    password : str
        password
    url : str
        url of the ENT

    Returns
    -------
    cookies : cookies
        returns the ent session cookies
    """
    if not url:
        print("Missing url attribute")
        return

    print(f"[ENT {url}] Logging in with {username}")

    # ENT Connection
    with requests.Session() as session:
        payload = {"email": username, "password": password}
        r = session.post(url, headers=HEADERS, data=payload)

        if "login" in r.url:
            print(
                f"Fail to connect with Open NG {url} : probably wrong login information"
            )
            return

        return session.cookies

print(_open_ent_ng(url="https://ent77.seine-et-marne.fr/auth/login", username="oenvdhdkdv", password="odjvdjd"))
```

**Comment by SleepInfinity** [comment]
> for information, the error I have with example.py
> 
> ```
>   File "g:\Mon Drive\Domotique\Pronote\pronotepy-master\pronotepy-master\example.py", line 5, in <module>
>     client = pronotepy.Client('https://0772190m.index-education.net/pronote/eleve.html',
>   File "g:\Mon Drive\Domotique\Pronote\pronotepy-master\pronotepy-master\pronotepy\clients.py", line 436, in __init__
>     super().__init__(pronote_url, username, password, ent, mode, uuid)
>   File "g:\Mon Drive\Domotique\Pronote\pronotepy-master\pronotepy-master\pronotepy\clients.py", line 96, in __init__
>     self.attributes, self.func_options = self.communication.initialise()
>   File "g:\Mon Drive\Domotique\Pronote\pronotepy-master\pronotepy-master\pronotepy\pronoteAPI.py", line 77, in initialise
>     self.attributes = self._parse_html(get_response.content)
>   File "g:\Mon Drive\Domotique\Pronote\pronotepy-master\pronotepy-master\pronotepy\pronoteAPI.py", line 264, in _parse_html
>     raise PronoteAPIError(
> pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
> ```
> 
> with the config below:
> 
> ```
> import pronotepy
> from pronotepy.ent import ent77
> 
> # creating the client and passing the occitanie_montpellier function to automatically get cookies from ENT
> client = pronotepy.Client('https://0772190m.index-education.net/pronote/eleve.html',
>                           username='*****',
>                           password='*****',
>                           ent=ent77)
> ```

yes it is because your ent changed their default login page from ent77 to just ent.
i just added the 'referer': 'https://ent.seine-et-marne.fr/' to the headers and it works.
In your client object you just need to use the function i provided above instead of the default ent77 from pronotepy.

**Comment by yodn** [comment]
Very thanks !!! was able to get my script for Home Assistant working.
