### ISSUE TITLE
When stopping file aiohttp unclosed client session

### ISSUE THREAD

**Issue by rmenai007** [bain3/pronotepy#33]
So each time I close my file I get: aiohttp unclosed client session.
I looked in the documentation and everywhere but didn't find a close function.

So can you please implement one? thx

**Comment by bain3** [comment]
Hello,
pronotepy doesn't use aiohttp. This is not an async library.

**Comment by rmenai007** [comment]
But is there a way to close the session ?

**Comment by bain3** [comment]
The only session open is here: `Client.communication.session`, but that is not an `aiohttp` session...

**Comment by rmenai007** [comment]
Thanks Im using pronotepy in a discord bot, that why I think I got this error.
