### ISSUE TITLE
How to get the link of virtual classroom

### ISSUE THREAD

**Issue by Bapt5** [bain3/pronotepy#34]
Hi I'm trying to get the link of my virtual classroom (I have lots of virtual class especially during this period) but I think that this API can't get that. Do someone know how to get this information ?

**Comment by Bapt5** [comment]
@bain3 Do you have a solution ? The button you see in the screenshot give the link of the virtual classroom. 
![image](https://user-images.githubusercontent.com/63651713/114306119-1671bc80-9adb-11eb-8bcf-9e2845056a95.png)

**Comment by bain3** [comment]
Hello,
unfortunately there are no virtual classrooms in the demo of pronote so I cannot implement it by myself. I suspect its gonna be just a matter of adding a transformer to `Lesson.transformers` though. We need to know the id and I would guess the overall structure of the "Contenu". Could you (or anyone) send me an output of this script (change all the personal info ofc)?
```py
import pronotepy
import datetime
# just for formatting
try:
    from pprint import pp as print
except ImportError:
    pass

# -- REPLACE --
# find a lesson with a virtual classroom and put its starting date and time here
LESSON_START = datetime.datetime(hour=9, minute=0, day=5, month=4, year=2021)
PRONOTE = 'https://demo.index-education.net/pronote/eleve.html'
USERNAME = 'demonstration'
PASSWORD = 'pronotevs'
# -- REPLACE END --

client = pronotepy.Client(PRONOTE, username=USERNAME, password=PASSWORD)

# find any date on which you have a lesson with a virtual classroom (REPLACE)

if client.logged_in:
    # This is basically a copy from the Client.lessons method. We just need to log the actual json
    # received from pronote
    user = client.parametres_utilisateur['donneesSec']['donnees']['ressource']
    data = {
        "ressource": user,
        "avecAbsencesEleve": False, "avecConseilDeClasse": True,
        "estEDTPermanence": False, "avecAbsencesRessource": True,
        "avecDisponibilites": True, "avecInfosPrefsGrille": True,
        "Ressource": user,
        'NumeroSemaine': client.get_week(LESSON_START.date()),  # this is great btw, pronote API's consistency :P
        'numeroSemaine': client.get_week(LESSON_START.date())
    }

    response = client.post('PageEmploiDuTemps', 16, data)

    # find the specific lesson
    time_string = LESSON_START.strftime('%d/%m/%Y %H:%M:%S')
    for lesson in response['donneesSec']['donnees']['ListeCours']:
        if lesson["DateDuCours"]["V"] == time_string:
            print(lesson)
```

**Comment by Bapt5** [comment]
The output of this script is 
`{'N': '301F48D0928461',
 'G': 0,
 'P': 2641,
 'place': 8,
 'duree': 2,
 'DateDuCours': {'_T': 7, 'V': '26/04/2021 12:15:00'},
 'nbVisiosMaxProgrammes': 1,
 'listeVisios': {'_T': 24,
                 'V': [{'N': '186DDB3A68EDFF0',
                        'url': 'https://lycee.cned.fr/cv/223286/146'}]},
 'CouleurFond': '#C0C0C0',
 'ListeContenus': {'_T': 24,
                   'V': [{'L': 'ALLEMAND LV2', 'N': '815B09AFA35CBC', 'G': 16},
                         {'G': 3, 'L': 'MALEFANT I.'},
                         {'L': '[1ALL23 (1)]', 'N': '61BDAB26B1DB13', 'G': 2},
                         {'L': 'S107', 'N': '13626F3E24E1746', 'G': 17}]},
 'AvecTafPublie': False,
 'dispenseEleve': {'_T': 24,
                   'V': {'L': 'Enseignement à la maison du 26/04/2021 au '
                              '01/05/2021',
                         'maison': True}}}`
I think the link is in `lesson['listeVisios']['V'][0]['url']`

**Comment by bain3** [comment]
Can you please try it with latest release? I think I got it. 3d1b58f

**Comment by Bapt5** [comment]
Ok It's work thank you
