### ISSUE TITLE
Haute Garonne's ENT not avaible

### ISSUE THREAD

**Issue by jd-develop** [bain3/pronotepy#36]
The Haute Garonne's ENT is not avaible in pronotepy. I tried with occitanie_montpellier, but it returns an error.
The link of this ENT : https://ecollege.haute-garonne.fr

Regards,
Jean Dubois

**Comment by Xiloe** [comment]
Hey, I see that this ENT ressembles the occitanie one. You could use that as a base and make your own ENT and PR the changes. 

> but it returns an error

What's the error ?

**Comment by jd-develop** [comment]
I'm sorry for the late, I stopped worked on the project and I've deleted my code...
I close the issue.

Goodbye :)
Jean Dubois
