### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by Mattlau04** [bain3/pronotepy#37]
It says the "Start" attribute on Lessons objects is a str when it's a datetime object

**Comment by Mattlau04** [comment]
it also says that the canceled and outing attributes are Bools, but they return None for me, so it should probably be an union

**Comment by bain3** [comment]
Hello, sorry for the inconvenience. Unfortunately Pronote's API is also quite inconsistent, so its not easy to give consistent results.
I have changed the json parser that it should either be giving some preset default values, trying to give a default value of the converter function, or None as a fallback. You can install the latest version by following the steps in README.
