### ISSUE TITLE
Discussion support

### ISSUE THREAD

**Issue by ebanDev** [bain3/pronotepy#41]
Hello, I would like to make a bridge between discord, and pronote discussions, do you plan to implement conversation support?

**Comment by bain3** [comment]
Hello,
unfortunately I am not able to implement discussions now. I no longer have access to a normal pronote account.

**Comment by ebanDev** [comment]
Oh too bad :/ If ever I can help you thanks to my pronote account don't hesitate ;)

**Comment by Bapt5** [comment]
I'm afraid that the bridge between discord and Pronote is a little too specific and does not correspond to all. But we can try to send message data to a discord bot in the form of JSON and receive messages from discord in the form of JSON and redirect them to Pronote @ebanDev 
I can try to implement that when I have some time.

**Comment by Bapt5** [comment]
I have no idea how to make that we choose the person to whom the message is sent. Has someone an idea please ?

**Comment by BugBoys100** [comment]
Hello, I'm developing a discord adaptation to this module, if you want, I'll put it on my Github probably next week, the only problem I'm having is accessing the client's schedule, if could someone help me...

**Comment by Bapt5** [comment]
@BugBoys100 Yep no problem i think i can help you.
