### ISSUE TITLE
Lessons with several teachers

### ISSUE THREAD

**Issue by JulesGrd** [bain3/pronotepy#47]
requests for lessons with several teachers and / or several groups and / or several classrooms only return the name of the first group or classroom and the name of the first teacher in the list
![image](https://user-images.githubusercontent.com/77736557/124391295-32f34e80-dcf0-11eb-83fc-38dd1b747359.png)

**Comment by bain3** [comment]
This requires some reworking of the transformer system in `pronotepy.Lesson`. I can't see any lessons with multiple teachers on the demo website so I am not able to fix it.
