### ISSUE TITLE
How can I use the acquisitions for the evaluations ?

### ISSUE THREAD

**Issue by LeTailleCrayon** [bain3/pronotepy#48]
Hello,
I've tried to use evaluations.acquisitions, but it returns me that : 
[<pronotepy.dataClasses.Acquisition object at 0x000001DDB04AA640>]
[<pronotepy.dataClasses.Acquisition object at 0x000001DDB04AA740>]
[<pronotepy.dataClasses.Acquisition object at 0x000001DDB04AA940>, <pronotepy.dataClasses.Acquisition object at 0x000001DDB04AA9C0>, <pronotepy.dataClasses.Acquisition object at 0x000001DDB04AA8C0>, <pronotepy.dataClasses.Acquisition object at 0x000001DDB04AA840>]

Can you help me please ?
Thank you in advance

**Comment by bain3** [comment]
Hi, `evaluation.acquisitions` returns a List of `pronotepy.Acquisition` objects, which is what you are currently seeing in the console. 

To access information about each acquisition, you first need to pick one from the list and then access its attributes. You can consult the [docs](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.dataClasses/#pronotepy.dataClasses.Acquisition) to check what information the Acquisition object has.

Example:
```py
for acquisition in evaluation.acquisitions:
    print(f"{acquisition.name}: {acquisition.level}")
```
This prints the name and the level achieved for each acquisition.
