### ISSUE TITLE
ent bretagne

### ISSUE THREAD

**Issue by zazou-du22** [bain3/pronotepy#50]
hello, just a question, the ENT bretagne-rennes is not implemented in pronotepy? If this is indeed the case, is there a way to implement it?

**Comment by vicllo** [comment]
Hello,
If your ent is not implemented yet, there is a good probability that its login system is similar to another one.
Take a look at the other ent in `ent.py`, and maybe you will be able to implement your ent as well.
Here is an usefull link : 
[https://github.com/bain3/pronotepy/issues/36](url)

**Comment by tarneaux** [comment]
Try copy-pasting the ENT functions for your region and modifying the links (like the login page's) to yours.

**Comment by Bapt5** [comment]
@zazou-du22 This ENT was implemented in #96
