### ISSUE TITLE
Changements pour 2021/2022

### ISSUE THREAD

**Issue by Androz2091** [bain3/pronotepy#54]
Salut,
Savez-vous si la lib supportera la prochaine version de Pronote ?

**Comment by tarneaux** [comment]
Salut,
Si mon établissement met pronote à jour vers la version 2021 cette année, je développerai une nouvelle version de pronotepy.
Sinon avec un peu de chance la nouvelle version sera compatible... On peut toujours prier...

**Comment by Androz2091** [comment]
> Salut,
Si mon établissement met pronote à jour vers la version 2021 cette année, je développerai une nouvelle version de pronotepy.
Sinon avec un peu de chance la nouvelle version sera compatible... On peut toujours prier...

> Edit: si tu t'y connais un poil en web scraping hésite pas à aider, une personne de plus c'est toujours bien

Yep, perso je maintiens une lib javascript (https://github.com/EduWireApps/pronote-api), mais je peux également aider les autres projets si jamais l'API change 👍 
il me semble que https://demo.index-education.net/pronote doit inclure les changements, non ?

**Comment by tarneaux** [comment]
Absolument raison, si on survole le pronote en haut à droite il est vrai que ça dit "pronote 2021"...
J'ai un peu l'impression que c'est toujours le même néanmoins (en tout cas l'exemple de pronotepy fonctionne encore).
Est-ce que ça serait pas plutôt la version 2020/2021?
Je crois qu'on verra demain à la rentrée.
