### ISSUE TITLE
ENT rework

### ISSUE THREAD

**Issue by bain3** [bain3/pronotepy#56]
Most ENTs share the same login system. It would be great if we had one master function, then other functions would just derive from it, basically wrapping it.

Also the `cookiejar_from_dict` methods all over the place could probably be done differently.

**Comment by Xiloe** [comment]
Todo : Support Educonnect, and all the other ways to connect to ENTs since not everyone has an ATEN account.

**Comment by OiseauDesPlages** [comment]
from what i understand the ents share the same login system but the way to get to the educonnect page is different.

**Comment by OiseauDesPlages** [comment]
From what i understand the ENTs share the same login system but the way to get to the Educonnect page is different, is it possible to manage all ENTs with one function?

**Comment by OiseauDesPlages** [comment]
On the pronote application, after connecting for the first time, it manages to reconnect automatically at each connection even with an ent. Maybe there is a way to do the same thing.
I tried to figure out how it worked but couldn't.

**Comment by Bapt5** [comment]
@OiseauDesPlages Yes but we already do it we save the hash of the password and I think the Pronote app does the same thing
