### ISSUE TITLE
login api with Educonnect

### ISSUE THREAD

**Issue by JulesLePrince** [bain3/pronotepy#57]
How can I connect with an educonnect account? The pronote of my lycée doesn't allow me to connect otherwise.

**Comment by Xiloe** [comment]
On mine I can connect using the legacy user:password you can still try loging in on pronote directly, by adding ?login)true at the end of the url like so : https://XXXXXXXXX.index-education.net/pronote/eleve.html?login=true

**Comment by Xiloe** [comment]
Else you need to wait for someone to add the EduConnect login method support, or do it yourself. Since I also have it I'll give it a try, I won't promise anything though since I did not used python in a while lmao

**Comment by Bapt5** [comment]
Already done #73 
Please use
```python
client = pronotepy.Client('https://0000000a.index-education.net/pronote/eleve.html',
                          username='demonstration',
                          password='pronotevs',
                          ent=educonnect)
```

**Comment by JulesLePrince** [comment]
Thanks a lot I didn't noticed it in the doc. However, I still have an error : 
```
File "/Users/julesleprince/code/Pronote/pronote_api.py", line 12, in <module>
    client = pronotepy.Client('https://0352009u.index-education.net/pronote/eleve.html', username='myusername', password='mypassword', ent=educonnect)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 283, in __init__
    super().__init__(pronote_url, username, password, ent)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 50, in __init__
    cookies = ent(username, password)

TypeError: educonnect() missing 2 required positional arguments: 'username' and 'password'
```

**Comment by OiseauDesPlages** [comment]
If tour ent use educonnect, tout can't directly login to educonnect, tout nées to pass throught tour school first which will redirect you to educonnect with an unique URL. To make the educonnect fonction working you need to create create another ent fonction that will handle tour s

**Comment by OiseauDesPlages** [comment]
If your ENT uses educonnect, you cannot connect directly to educonnect, you must first go through your school's website which will redirect you to educonnect with a unique URL. For the educonnect function to work, you need to create another ENT function that will handle getting the unique URL through your school site. Then you can call the educonnect function which will take care of the educonnect authentication.

**Comment by OiseauDesPlages** [comment]
For exemple this is the ac_grenoble ent function:
`identity_provider = "https://cas.ent.auvergnerhonealpes.fr/login?selection=EDU&service=https://0380029A.index-education.net/pronote/&submit=Confirm"
    login_service_provider = "https://educonnect.education.gouv.fr/idp/profile/SAML2/POST/SSO"

    # Required Headers
    headers = {
        'connection': 'keep-alive',
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0'}

    # SAML authentication
    session = requests.Session()
    response = session.get(identity_provider, headers=headers)

    soup = BeautifulSoup(response.text, 'html.parser')
    payload = {
        "RelayState": soup.find("input", {"name": "RelayState"})["value"],
        "SAMLRequest": soup.find("input", {"name": "SAMLRequest"})["value"]
    }

    log.debug('[ENT Eaux claires] Logging in with ' + username)
    response = session.post(login_service_provider, data=payload, headers=headers)

    cookies = requests.utils.cookiejar_from_dict(requests.utils.dict_from_cookiejar(session.cookies))
    return educonnect(response.url, cookies, username, password)`

**Comment by OiseauDesPlages** [comment]
For exemple this is the ac_grenoble ent function:

https://github.com/bain3/pronotepy/blob/master/pronotepy/ent.py#L56

**Comment by Bapt5** [comment]
Okay, I will do it 
@bain3 can you assigne me this please ?

**Comment by Bapt5** [comment]
@JulesLePrince what is your ENT? (url, link of educonnect...)

**Comment by JulesLePrince** [comment]
I login through educonnect : https://educonnect.education.gouv.fr/idp/profile/SAML2/Redirect/SSO?execution=e2s1
And I found a pronote link : https://0352009u.index-education.net/pronote/
and also a toutatice link : https://www.toutatice.fr/portail

**Comment by Bapt5** [comment]
@JulesLePrince Okay Thanks 
Is Toutatice your ENT?

**Comment by JulesLePrince** [comment]
@Bapt5 Yep it is

**Comment by Bapt5** [comment]
@JulesLePrince Could you please install my version of pronotepy to do some test? 
```console
pip install git+https://github.com/Bapt5/pronotepy.git
```
And then execute this python script
```python
import pronotepy
from pronotepy.ent import ac_rennes

client = pronotepy.Client('https://0352009u.index-education.net/pronote/eleve.html',
                          username='yourusername',
                          password='yourpassword',
                          ent=ac_rennes)

if client.logged_in:
    # get the all the periods (may return multiple types like trimesters and semesters but it doesn't really matter
    # the api will get it anyway)
    periods = client.periods

    for period in periods:
        for grade in period.grades:  # iterate over all the grades
            print(f'{grade.grade}/{grade.out_of}')  # print out the grade in this style: 20/20
else:
    print('Not log in')

```
If your grades is not print, please send me the error.

**Comment by JulesLePrince** [comment]
I still have an error after updating pronotepy from your repository : 
```
Traceback (most recent call last):

  File "/Users/julesleprince/code/Pronote/pronote.py", line 12, in <module>
    client = pronotepy.Client('https://0352009u.index-education.net/pronote/eleve.html',

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 283, in __init__
    super().__init__(pronote_url, username, password, ent)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 50, in __init__
    cookies = ent(username, password)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/ent.py", line 121, in ac_rennes
    return educonnect(response.url, cookies, username, password)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/ent.py", line 31, in educonnect
    "RelayState": soup.find("input", {"name": "RelayState"})["value"],

TypeError: 'NoneType' object is not subscriptable
```

**Comment by Bapt5** [comment]
Okay thanks I'm sorry to ask you to do some tests, but I haven't any Toutatice or Educonnect account. So, it's difficult for me to test my work. Do you know if there is any demo account? @JulesLePrince 

![image](https://user-images.githubusercontent.com/63651713/154272456-859468c5-6fd6-4a76-bff3-7c4b55c41a5b.png)
For the connection do we agree that you click on the educonnect button? and then you enter your information of educonnect account and then you are redirected to Toutatice where you can go on Pronote?

**Comment by Bapt5** [comment]
Yes no problem, I understand, I don't want you send me your password because it's not very secure. But we may have to do a lot of testing. Do you prefer to communicate on another platform where you would be more responsive? Or is GitHub just right for you? @JulesLePrince

**Comment by JulesLePrince** [comment]
@Bapt5 I think we can stay on GitHub
 I found why the api raise the error  `'NoneType' object is not subscriptable `. I don't know why but when I use the same session in the functions `ac_rennes()` and `educonnect()` I'm able to connect and the cookies of the connected session are return by `educonnect()` 

<details>
  <summary>The code that worked for me</summary>

  ```
  import requests
from bs4 import BeautifulSoup

username = 'myusername'
password = 'mypassword'

# Toutatice required URL
toutatice_url = "https://www.toutatice.fr/portail/auth/MonEspace"
toutatice_login = "https://www.toutatice.fr/wayf/Ctrl"

# Required Headers
headers = {
    'connection': 'keep-alive',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0'}

session = requests.Session()

response = session.get(toutatice_url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')
payload = {
    "entityID": soup.find("input", {"name": "entityID"})["value"],
    "return": soup.find("input", {"name": "return"})["value"],
    "_saml_idp": soup.find("input", {"name": "_saml_idp"})["value"]
}


response = session.post(toutatice_login, data=payload, headers=headers)

cookies = requests.utils.cookiejar_from_dict(requests.utils.dict_from_cookiejar(session.cookies))
url = response.url

payload = {
    "j_username": username,
    "j_password": password,
    "_eventId_proceed": ""
}

# Send user:pass to Educonnect
#session = requests.session()

response = session.post(url, headers=headers, data=payload, cookies=cookies)

# 2nd SAML Authentication
soup = BeautifulSoup(response.text, 'html.parser')

payload = {
    "RelayState": soup.find("input", {"name": "RelayState"})["value"],
    "SAMLResponse": soup.find("input", {"name": "SAMLResponse"})["value"]
}

cookies = requests.utils.cookiejar_from_dict(requests.utils.dict_from_cookiejar(session.cookies))
session.post(soup.find("form")["action"], headers=headers, data=payload, cookies=cookies)
print(requests.utils.cookiejar_from_dict(requests.utils.dict_from_cookiejar(session.cookies)))

  ```
</details>


However when trying the demo code you gave me, `client.logged_in` method failed with : 
```

  File "/Users/julesleprince/code/Pronote/pronote.py", line 4, in <module>
    client = pronotepy.Client('https://0352009u.index-education.net/pronote/',

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 283, in __init__
    super().__init__(pronote_url, username, password, ent)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 58, in __init__
    self.attributes, self.func_options = self.communication.initialise()

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/pronoteAPI.py", line 60, in initialise
    self.attributes = self._parse_html(get_response.content)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/pronoteAPI.py", line 203, in _parse_html
    raise PronoteAPIError(

PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```

**Comment by Bapt5** [comment]
@JulesLePrince Yes but the code you give me is exactly the code in pronotepy so I don't understand why it doesn't work😭

**Comment by Bapt5** [comment]
@JulesLePrince But the error you give me is not the same as yesterday so I know why it doesn't work

**Comment by Bapt5** [comment]
@JulesLePrince Okay I found the problem We must use the same Session in all function. I will correct that this evening and I tell you when it's good

**Comment by Bapt5** [comment]
@JulesLePrince I think It's good now !!
Please do the same think like yesterday but change the pronote url like in my script

```console
pip install git+https://github.com/Bapt5/pronotepy.git
```
And then execute this python script
```python
import pronotepy
from pronotepy.ent import ac_rennes

client = pronotepy.Client('https://0352009u.index-education.net/pronote/',
                          username='yourusername',
                          password='yourpassword',
                          ent=ac_rennes)

if client.logged_in:
    # get the all the periods (may return multiple types like trimesters and semesters but it doesn't really matter
    # the api will get it anyway)
    periods = client.periods

    for period in periods:
        for grade in period.grades:  # iterate over all the grades
            print(f'{grade.grade}/{grade.out_of}')  # print out the grade in this style: 20/20
else:
    print('Not log in')

```

**Comment by JulesLePrince** [comment]
@Bapt5 It seems to connect but I steal have the error : 
```
Traceback (most recent call last):

  File "/Users/julesleprince/code/Pronote/pronote.py", line 4, in <module>
    client = pronotepy.Client('https://0352009u.index-education.net/pronote/',

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 290, in __init__
    super().__init__(pronote_url, username, password, ent)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/clients.py", line 59, in __init__
    self.attributes, self.func_options = self.communication.initialise()

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/pronoteAPI.py", line 67, in initialise
    self.attributes = self._parse_html(get_response.content)

  File "/opt/homebrew/lib/python3.9/site-packages/pronotepy/pronoteAPI.py", line 209, in _parse_html
    raise PronoteAPIError(

PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.
```

**Comment by bain3** [comment]
Hi,
the error you got [here](https://github.com/bain3/pronotepy/issues/57#issuecomment-1041895478) is probably because you pasted the url without the `eleve.html` ending. This should be probably done differently though when I look at it. I might change it to make it more fool proof (not calling you a fool btw lol).

**Comment by JulesLePrince** [comment]
Hi, 
Got the same error with the new url :
`
`

**Comment by bain3** [comment]
Yeah then its a problem with cookies. The url should now be fine

**Comment by Bapt5** [comment]
I think the cookies are good. Because I tried and the page is return when I call Pronote is a page where is write "Toutatice Authentication en cours"

**Comment by JulesLePrince** [comment]
Any Idea how to resolve the problem?

**Comment by Bapt5** [comment]
No for the moment @JulesLePrince Have you ever seen a page like that when your are connecting on Pronote?

**Comment by JulesLePrince** [comment]
@Bapt5 Nop I access pronote through toutatice and the waiting page looks like this : 

<img width="985" alt="Screenshot 2022-02-16 at 22 11 48" src="https://user-images.githubusercontent.com/31992334/154358032-2a32c6e3-dd89-496b-9cb5-7823891b2134.png">

**Comment by JulesLePrince** [comment]
After some research I found it. 

<img width="1286" alt="Screenshot 2022-02-16 at 22 28 33" src="https://user-images.githubusercontent.com/31992334/154360201-d8bb9e4c-1d2d-4226-bf9a-1d55e3389978.png">

**Comment by Bapt5** [comment]
@JulesLePrince Okay Is it just after you click to access Pronote?

**Comment by JulesLePrince** [comment]
@bain3 yep after entering my username / password

**Comment by Bapt5** [comment]
Wait excuse me I'm not sure I understand. It's after you enter your username or it's after you click on the button in your ENT to go on Pronote? @JulesLePrince

**Comment by JulesLePrince** [comment]
@Bapt5 
When I go to my pronote webpage I'm asked to choose an auth method I choose Educonnect. If I'm already connected to edcuonnect the message appears directly else I'm asked to ender my username and password and the message appears.

**Comment by Bapt5** [comment]
@JulesLePrince Is there another page in your ENT where you see the page "Authentification" before accessing it? If yes, could you please send me the link?

**Comment by Bapt5** [comment]
I've tried another think. @JulesLePrince Could you test like in this [comment](https://github.com/bain3/pronotepy/issues/57#issuecomment-1041917562) please?

**Comment by JulesLePrince** [comment]
> @JulesLePrince Does it work ?

Yes it works now. Thanks a lot :)
