### ISSUE TITLE
Add Ac-reims cas

### ISSUE THREAD

**Issue by Alestrio** [bain3/pronotepy#6]
Hi,
Can you please add the Reims CAS for that API ?
I plan to use it in a Discord bot during the containment, and Litarvan's API doesn't work with that CAS.
It could also be better to use it as I'm developping with Python

Thanks,

**Comment by Xiloe** [comment]
Hey! please add me on discord Xiloe#9854

**Comment by Alestrio** [comment]
Sorry, you are not accepting people to add you as friends. You can add me Alestrio#7611
Thanks for your quick reply,

**Comment by Xiloe** [comment]
Oh, yes my bad..

**Comment by Alestrio** [comment]
implemented in 8bf95061eefa42ba8d1f7bdae7bd5f533fe86ebc
