### ISSUE TITLE
ENT Occitanie is out of date

### ISSUE THREAD

**Issue by ASPJulien** [bain3/pronotepy#62]
Hello, my python is not that good I'll not be able to help you with that problem but, ent occitanie looks out of date.
It searches for an id_body that is not available, I guess that it's because the login page changed.

**Comment by ASPJulien** [comment]
oh I forgot, the error is this: "pronotepy.exceptions.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page."

**Comment by ASPJulien** [comment]
And the pronote page I'm using is "https://0340118u.index-education.net/pronote/eleve.html"

**Comment by Xiloe** [comment]
Hey, I know it is broke, and I am working on it. It is working on the new ENT system, but I did not implemented it in the old yet, basically they removed some of their verification stuff.


Here is my current code if you want to implement it yourself. I added comments to tell you what casURL, atenURL and origURL are since you don't have them.

```py
import requests
from bs4 import BeautifulSoup

headers = {
        'connection': 'keep-alive',
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0'}

payload = {
        'auth_mode': 'BASIC',
        'orig_url': '',
        'user': '',
        'password': ''}

def login(casURL, atenURL, origURL, username, password):
    # atenURL =  "famille.ac-montpellier.fr"
    # casURL = "cas.mon-ent-occitanie.fr"
    # origURL = "/fim42/sso/SSO?SPEntityID=sp-ent-entmip-prod"

    login_url = f'https://{atenURL}/login/ct_logon_vk.jsp?CT_ORIG_URL={origURL}&ct_orig_uri={origURL}'
    saml_url  = f'https://{casURL}/saml/SAMLAssertionConsumer'

    p = payload
    p['user'] = username
    p['password'] = password
    p['orig_url'] = origURL

    # Get the initial cookies and orig_url bullshit
    session = requests.Session()

    # Send the username and password to ATEN and get the hidden input values
    response = session.post(login_url, headers=headers, data=payload)

    soup = BeautifulSoup(response.text, 'html.parser')
    cas_infos = dict()

    inputs = soup.findAll('input', {'type': 'hidden'})
    for input_ in inputs:
        cas_infos[input_.get('name')] = input_.get('value')

    # Finally connect
    session.post(saml_url, headers=headers, data=cas_infos)

    # Return the cookies
    return requests.utils.cookiejar_from_dict(requests.utils.dict_from_cookiejar(session.cookies))
```

**Comment by ASPJulien** [comment]
and sorry this may be my fault this time, but it still doesn't work for me
![image](https://user-images.githubusercontent.com/49618271/135765837-90fd04a4-ace6-435f-8264-f0be1e581372.png)

**Comment by Xiloe** [comment]
It works fine for me though, unless you find a fix (or someone else does) you will need to wait until I finish the new ENT stuff

**Comment by ASPJulien** [comment]
Still the same error
If you ever need creditentials to try to fix it one day go in DM 👍

**Comment by YoYomec** [comment]
> Hé, je sais que c’est cassé, et j’y travaille. Il travaille sur le nouveau système ORL, mais je ne l’ai pas encore mis en œuvre dans l’ancien, en gros, ils ont supprimé certains de leurs éléments de vérification.
> 
> Voici mon code actuel si vous souhaitez l’implémenter vous-même. J’ai ajouté des commentaires pour vous dire ce que sont casURL, atenURL et origURL puisque vous ne les avez pas.
> 
> ```python
> import requests
> from bs4 import BeautifulSoup
> 
> headers = {
>         'connection': 'keep-alive',
>         'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0'}
> 
> payload = {
>         'auth_mode': 'BASIC',
>         'orig_url': '',
>         'user': '',
>         'password': ''}
> 
> def login(casURL, atenURL, origURL, username, password):
>     # atenURL =  "famille.ac-montpellier.fr"
>     # casURL = "cas.mon-ent-occitanie.fr"
>     # origURL = "/fim42/sso/SSO?SPEntityID=sp-ent-entmip-prod"
> 
>     login_url = f'https://{atenURL}/login/ct_logon_vk.jsp?CT_ORIG_URL={origURL}&ct_orig_uri={origURL}'
>     saml_url  = f'https://{casURL}/saml/SAMLAssertionConsumer'
> 
>     p = payload
>     p['user'] = username
>     p['password'] = password
>     p['orig_url'] = origURL
> 
>     # Get the initial cookies and orig_url bullshit
>     session = requests.Session()
> 
>     # Send the username and password to ATEN and get the hidden input values
>     response = session.post(login_url, headers=headers, data=payload)
> 
>     soup = BeautifulSoup(response.text, 'html.parser')
>     cas_infos = dict()
> 
>     inputs = soup.findAll('input', {'type': 'hidden'})
>     for input_ in inputs:
>         cas_infos[input_.get('name')] = input_.get('value')
> 
>     # Finally connect
>     session.post(saml_url, headers=headers, data=cas_infos)
> 
>     # Return the cookies
>     return requests.utils.cookiejar_from_dict(requests.utils.dict_from_cookiejar(session.cookies))
> ```

Hello, I have a problem : in this code, i wont to know how you get the  origURL value
