### ISSUE TITLE
Eclat-BFC  

### ISSUE THREAD

**Issue by portalthree** [bain3/pronotepy#65]
Hello! I don't really know what I need to submit a ent request, but here's the login page:
https://cas.eclat-bfc.fr/login?service=https:%2F%2F0250007X.index-education.net%2Fpronote%2Feleve.html
I tried to implement it on my own but I don't really get how i'm supposed to do it

**Comment by Xiloe** [comment]
Looks like it uses the same base as the Occitanie ENT, you might wanna try to use it. And if it doesn't work, try implementing the code I sent on #62

**Comment by Xiloe** [comment]
It in fact does use ATEN to login. But right now I did not implemented any other way of logging in. So you will have to die it yourself, or wait for the ENT update I'm working on.
