### ISSUE TITLE
Issue with contents

### ISSUE THREAD

**Issue by Alestrio** [bain3/pronotepy#7]
Hi,
There might be an issue with the content feature. (lessons)
When called with 
`lessons = self.client.lessons(datetime.date.today()) print(lessons.content)` 
or
`lessons = self.client.lessons(datetime.date.today()) print(lessons.content())` 
the interpreter says it is null, however it is not (see https://hastebin.com/raw/eqediteteb)
After further investigation, it seems that the issue comes with 
`if lesson['cours']['V']['N'] == self.id:
                contents = lesson['listeContenus']['V'][0]`
because that self.id isn't in the returned JSON.

Cordially,

**Comment by bain3** [comment]
Hello,
`pronotepy.Client.lessons()` returns a `list` of `pronotepy.Lesson`. Are you sure that you're using this method correctly? In the example above, you're trying to get the `content` attribute of `list` which of course doesn't exist.

**Comment by Alestrio** [comment]
Yeah my example was a bit weird, but here is another who does the same thing :
`for le in lessons:
      print(le.content().description)`

**Comment by bain3** [comment]
This happens when the lesson doesn't actually have any description. Pronote will not send you anything, because it actually doesn't have to show you anything in the *Contenu et ressources* tab. Returning `None` in this case is fine.

**Comment by bain3** [comment]
Also, i should warn you that the `content` attribute is inefficient and every time you are making a request for the content, it will make a request to pronote. This shouldn't trigger anything on pronote's servers, but there is still a risk of getting your IP suspended.
