### ISSUE TITLE
Adding the Pays de la Loire "E-lyco" ENT to ent.py

### ISSUE THREAD

**Issue by shadowdevfr** [bain3/pronotepy#70]
Hello, is it possible to add the Pays de la Loire ENT called "e-lyco"? 

https://www.e-lyco.fr/

**Comment by OiseauDesPlages** [comment]
Hi, I have a script to start with but I don't know what happens once you log in to Educonnect, it's different for each school and I have no way of knowing but if this script can help you:

```
import requests
from bs4 import BeautifulSoup


headers = {
    'connection': 'keep-alive',
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0'}
    

url = "https://cas3.e-lyco.fr/discovery/WAYF?entityID=https%3A%2F%2Fcas3.e-lyco.fr%2Fshibboleth&returnX=https%3A%2F%2Fcas3.e-lyco.fr%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253Ad86ff322023918a01f987190fc64e21517c4e1b9090d559300864c2af1f7dab2&returnIDParam=entityID&action=selection&origin=https%3A%2F%2Feduconnect.education.gouv.fr%2Fidp"

session = requests.session()
response = session.get(url)
print(response.url)
ent_login = response.url

# Login payload

payload = {
"j_username": "username",
"j_password": "password",
"_eventId_proceed": ""
}
# Send user:pass to the ENT

cookies = requests.utils.cookiejar_from_dict(requests.utils.dict_from_cookiejar(session.cookies))
response = session.post(ent_login, headers=headers, data=payload, cookies=cookies)
```

**Comment by shadowdevfr** [comment]
The execution of this script returns the redirection page before accessing pronote, but now, as i'm kinda bad at python I would love to know if someone knows how to use the last request session and send the form params for login. After the login, the returned html is:
`<!DOCTYPE html><html>

<head>
    <meta charset="utf-8" />
</head>

<body onload="document.forms[0].submit()"> <noscript> <p> <strong>Note:</strong> Since your browser does not
            support JavaScript, you must press the Continue button once to proceed. </p> </noscript>  <form
        action="https://cas3.e-lyco.fr/Shibboleth.sso/SAML2/POST" method="post"> <div>
            <input type="hidden" name="RelayState"
                value="ss:mem:(string that looks like an v4 identifier here)" />  
            <input type="hidden" name="SAMLResponse"
                value="(Long string that looks like encrypted stuff here)">
             </div> <noscript> <div> <input type="submit" value="Continue" /> </div> </noscript> </form>
</body>

</html>`
(I changed the values because idk if it can be used to access my account)

**Comment by shadowdevfr** [comment]
Update: I managed to authentificate with the POST fields shown before. Now I get the final "Successfully authentificated!" from e-lyco! 
```
print("Connecting with SOs")
soup = BeautifulSoup(response.content, 'html.parser')

RelayState=soup.find("input", {"name": "RelayState"})
print(RelayState["value"])

SAMLresp=soup.find("input", {"name": "SAMLResponse"})
print(SAMLresp["value"])
payload = {
"RelayState": RelayState["value"],
"SAMLResponse": SAMLresp["value"],
}
print("Posting to the redirection handler")
response = session.post("https://cas3.e-lyco.fr/Shibboleth.sso/SAML2/POST", headers=headers, data=payload, cookies=cookies)
print(response.content)
print("Going to pronote with the authentificated session")
response = session.get("<pronote>.index-education.net/pronote/eleve.html", headers=headers, cookies=cookies)
print(response.content)
```
And boom! Successfully authentificated on pronote! 
Thanks for helping me!
