### ISSUE TITLE
It seems the homework function does not work.

### ISSUE THREAD

**Issue by apprehensivetarget** [bain3/pronotepy#75]
I am using this script to download my homework, but it does not seem to work. Any help would be greatly appreciated.

```import pronotepy
import datetime as DT
from time import sleep

today = DT.date.today()
week = today + DT.timedelta(days=7)

# initialising the client
client = pronotepy.Client(
    "https://1320002k.index-education.net/pronote/eleve.html",
    username="Redacted",
    password="Redacted",
)

# user login check
if client.logged_in:
    homework = client.homework(today, week)
   print(homework)
```
outputs ``[<pronotepy.dataClasses.Homework object at 0x7f9145b190>, <pronotepy.dataClasses.Homework object at 0x7f9145b430>, <pronotepy.dataClasses.Homework object at 0x7f9145b510>]``

**Comment by OiseauDesPlages** [comment]
Homework is an object not a string, homework object have attributs like "description", "subject" or "done". You can try with "print(homework.description)" for example.
