### ISSUE TITLE
How to post data to pronote interface ?

### ISSUE THREAD

**Issue by matteosev** [bain3/pronotepy#8]
Hi,

I was going through your code in pronotepy/pronotepy/pronoteAPI.py but i did not understand how you post data to pronote interface in order to authenticate the user. Can I ask some explanations ?

**Comment by bain3** [comment]
Hello,
pronotepy needs to do all the challenges the same way as the browser. The authentication code is [here](https://github.com/bain3/pronotepy/blob/master/pronotepy/pronoteAPI.py#L89). Throughout the whole library all the different functions use the [`_Communication` class](https://github.com/bain3/pronotepy/blob/master/pronotepy/pronoteAPI.py#L326), specifically [this](https://github.com/bain3/pronotepy/blob/master/pronotepy/pronoteAPI.py#L362) method. I hope this clarifies things a bit. If you have any more questions, feel free to ask.

**Comment by matteosev** [comment]
One of the part i didn't understand at all is [there](https://github.com/bain3/pronotepy/blob/cbbd431433d6fd621b173bd5864e3ed73d3f1e9d/pronotepy/pronoteAPI.py#L381) and especially this line :+1: 
`p_site = self.root_site + '/appelfonction/' + self.attributes['a'] + '/' + self.attributes['h'] + '/' + r_number`
What does that mean ? Why do you change the url ?

**Comment by bain3** [comment]
This is one of the great pronote things that no one but the developers can understand.
 - `self.root_site` = the root site (https://demo.index-education.net or your specific pronote)
 - `self.attributes['a']` = the espace (3 for students)
 - `self.attributes['h']` = session id
 - `r_number` = numeroOrdre (i don't know why they do it this way, but it does ensure that the client and the server are authenticated)

*Note: I did not choose to do it this way, pronotepy is only acting like a browser to gather all the data. I mostly just reversed engineered the javascript which is used by the browser.*

**Comment by matteosev** [comment]
OK, two first points understood, another little question, what is session id and why do you encrypt r_number ?

**Comment by bain3** [comment]
You get the session id from your initial connection. Pronote gives it to you in the page html. `r_number` is quite complicated. 
If you really need to understand the whole protocol, then @LelouBil has made a [good description of it](https://github.com/LelouBil/PronoteLib/blob/master/Protocol.md) (you need to understand french, but i suppose that you do).
The file is called eleve.js. The browser downloads it when you're connecting to the login page.

**Comment by matteosev** [comment]
I think i got it, i will use the LelouBil's protocol description to understand it, i don't take more of the _free time you have a bit to much_  ;-) 
Merci !

**Comment by LelouBil** [comment]
I wouldn't say that's a *good* description, I'll need to rework it a lot. Basicly it's a copy paste of my messages when I was explaining it to someone on discord so it might be hard to understand. Most information is there but if you're having troubles understanding it feel free to pm me on discord

**Comment by matteosev** [comment]
@LelouBil, oui ça fait un peu brouillon mais on arrive à saisir lepourquoi du comment, malheureusement j'ai pas les connaissances suffisantes en crypto (AES, sha256 j'y connais rien). Mais ton texte m'a aidé à comprendre comment le serveur authentifie les utilisateurs, je réessairai quand j'aurai de meilleures bases...
