### ISSUE TITLE
No module named pronotepy

### ISSUE THREAD

**Issue by Impre-visible** [bain3/pronotepy#81]
Bonjour/Bonsoir, j'ai installé pronotepy avec la commande du Github mais quand je lance le script de test, erreur, pronotepy n'est pas reconnu. Est-ce normal ?

**Comment by bain3** [comment]
Hello,
this doesn't look like a pronotepy issue. It looks like you have a messed up environment. I have tested both download links on two different machines and both of them worked. Please look into python environments and how to install packages through pip :)
