### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Mascode-Dev** [bain3/pronotepy#82]
I try to use the API with the code in README.md
I got the following error :
![image_2022-01-13_100339](https://user-images.githubusercontent.com/58656691/149309078-c5d472ba-d7a9-46e6-913a-9d9147c85c32.png)

I have already installed pronotepy with : pip install pronotepy 

What should I do?
Thanks for reading

**Comment by Aekyios** [comment]
"import pronotepy
from pronotepy import ent" does it work? for me yes

**Comment by Mascode-Dev** [comment]
nop that's doesn't work.. 

`import pronotepy
from pronotepy import ent


client = pronotepy.Client('https://XXXXXXXX.index-education.net/pronote/eleve.html?login=true',
                          username=' ',
                          password=' '
                          ent=' ',
)

if client.logged_in:
    print(len(client.messages())) # printing number of messages that the user has
else:
    print('no login')`

I obviously removed my IDs but here is my code

**Comment by bain3** [comment]
Hello,
this doesn't look like a pronotepy issue. It looks like you have a messed up environment. I have tested both download links on two different machines and both of them worked. Please look into python environments and how to install packages through pip :)
