### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by Aekyios** [bain3/pronotepy#83]
I use client=.... for my ent connexion
![Capture d’écran 2022-01-14 202924](https://user-images.githubusercontent.com/71457884/149590530-9a2a1e7f-6583-41bc-ad90-0ae1d25b2a0a.png)
![Capture d’écran 2022-01-14 203116](https://user-images.githubusercontent.com/71457884/149590533-82e3b4f5-4c29-4c3e-a3d9-28121fdc6cd0.png)

**Comment by bain3** [comment]
Hello,
this does not look like a direct problem with pronotepy. The trackeback tells you that `client` is a `RequestsCookieJar` instance. This means that the client was not properly created. Please refer to the [documentation](https://pronotepy.readthedocs.io/en/stable/quickstart/#client-initialisation) to see how to use and create a pronotepy client.

**Comment by Aekyios** [comment]
> Hello, this does not look like a direct problem with pronotepy. The trackeback tells you that `client` is a `RequestsCookieJar` instance. This means that the client was not properly created. Please refer to the [documentation](https://pronotepy.readthedocs.io/en/stable/quickstart/#client-initialisation) to see how to use and create a pronotepy client.

I use the command client = pronotepy.ent. MY ENT('username','password')
