### ISSUE TITLE
Pronote uses "Polling" instead of "Presence ?

### ISSUE THREAD

**Issue by Vexcited** [bain3/pronotepy#86]
Hello, I am making my own Pronote API on my side and I was watching the requests that Pronote makes.

I've seen that every two minutes, a request is made to `/appelpolling/<order>`.

That requests also longer two minutes.

Also, in the session from the HTML, you can see `poll: true`.

I didn't see anything about it in your code and in anyone code so I think that they get rid of Presence and use Polling ?

Or maybe I can try to still use Presence ?

I didn't tried at the moment, but I just want to ask to see if people have any answers ~

Thanks you !

**Comment by bain3** [comment]
Hello,
from what I can see polling is used for notifications. Presence is prpbably still used to keep the session alive. Although I didn't see any `/appelpolling/` requests on the demo website, I did search for it in the code and found this function: https://pastebin.com/w3qR2qmU.

**Comment by Vexcited** [comment]
Ok, I found out that on the demo they still uses Presence and there is no 'poll' key in the HTML object.

But for my school, and every other school (that I know), they give a 'poll: true' in the HTML, and there is no any Presence requests, only Polling

[Here](https://0870056n.index-education.net/pronote/eleve.html?login=true) is the Pronote URL for my school, I can even give you my credentials if you need more digging.

The Polling request looks the same as the Presence request tho

**Comment by Vexcited** [comment]
More informations about the polling request from my Network tab.

![Screenshot_20220131-074203_Kiwi Browser](https://user-images.githubusercontent.com/59152884/151749920-b9597604-fcaa-4c63-b286-4efa06595fac.jpg)
![Screenshot_20220131-074151_Kiwi Browser](https://user-images.githubusercontent.com/59152884/151749922-0d1d70ab-6f22-4938-a0d6-168a58c84207.jpg)
![Screenshot_20220131-074209_Kiwi Browser](https://user-images.githubusercontent.com/59152884/151749923-9abf95a4-956d-4879-a387-29ef6ff082fe.jpg)

Sorry if I'm on my phone; I'm currently going to school 😭

**Comment by bain3** [comment]
Yeah I guess the demo doesn't support notifications. I still think using presence is good enough for keeping alive the session. Technically you could use anything else, you just need to make requests. I think the requests look the same because there are no new notifications.
