### ISSUE TITLE
MQTT integration

### ISSUE THREAD

**Issue by vingerha** [bain3/pronotepy#87]
Hi, I have forked this rep. and plan to write an MQTT integration with it. I read that you are trying to hand over the maintenance but at present I cannot promise that I will be able to do that. Time and knowledge are at the moment sparsely available. When I am close to a working model we can discuss if you want to incorporate my work with yours ... or not.

**For now, much appreciating all the work you have done... THANKS!!**

**Comment by bain3** [comment]
Hello,
nice project. Unfortunately I don't think merging it would be a great idea. Pronotepy is meant to be a library for anything and adding MQTT is *very* specific. All the discord bots and other thingies people build don't need an MQTT integration. All that said it's still a cool project!
