### ISSUE TITLE
Add ENT for Essonne (Villemoisson sur Orge - Collège Blaise Pascal)

### ISSUE THREAD

**Issue by bran2000** [bain3/pronotepy#88]
Hello thanks for your work, is it possible to add  ENT for Essonne (Villemoisson sur Orge - Collège Blaise Pascal) ?
i have not the login and password to access directly to pronote, i only access with this URL:
[https://www.moncollege-ent.essonne.fr/](url) 
Thanks for your help
Best

**Comment by Bapt5** [comment]
already done #60 
Please use
```python
client = pronotepy.Client('https://0000000a.index-education.net/pronote/eleve.html',
                          username='demonstration',
                          password='pronotevs',
                          ent=ent_essonne)
```

**Comment by bran2000** [comment]
Thanks sorry I didn’t know
