### ISSUE TITLE
Task assignment

### ISSUE THREAD

**Issue by Bapt5** [bain3/pronotepy#89]
Hi @bain3 @Xiloe 
How can I assign myself tasks in the roadmap?

**Comment by bain3** [comment]
Hi,
I converted all the tasks to issues. You can just tell us what you want to work on and we'll assign it to you. Thanks!

**Comment by bain3** [comment]
Was #41 the issue you wanted to be assigned?

**Comment by Bapt5** [comment]
Okay thanks. Yes please I want to work on #41 But I wait until more information from @ebanDev
