### ISSUE TITLE
Can't detect pronote url

### ISSUE THREAD

**Issue by AlexZeGamer** [bain3/pronotepy#9]
I can't connect to Pronote with the [example.py](https://github.com/bain3/pronotepy/blob/master/example.py) code if I put my school's direct url (which is exactly like `https://0000000a.index-education.net/pronote/eleve.html`) instead of the demo one which works fine.

Error :
```Traceback (most recent call last):
  File "pronote.py", line 18, in <module>
    password='my-direct-pronote-password')
  File "C:\Users\Alexandre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pronotepy\pronoteAPI.py", line 61, in __init__
    self.attributes, self.func_options = self.communication.initialise()
  File "C:\Users\Alexandre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pronotepy\pronoteAPI.py", line 324, in initialise
    self.attributes = self._parse_html(get_response.content)
  File "C:\Users\Alexandre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pronotepy\pronoteAPI.py", line 462, in _parse_html
    "Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.")
pronotepy.pronoteAPI.PronoteAPIError: Page html is different than expected. Be sure that pronote_url is the direct url to your pronote page.```

**Comment by AlexZeGamer** [comment]
It seems like it only works if I put the `?login=true` that is at the end of the url
(`https://0000000a.index-education.net/pronote/eleve.html?login=true`)

**Comment by bain3** [comment]
Hello! Do you use an ent (cas) by any chance?

**Comment by bain3** [comment]
If you do, you can check if your ent is supported [here](https://pronotepy.readthedocs.io/en/stable/api/pronotepy.ent/). You can also find some example code for initialisation of your client [here](https://github.com/bain3/pronotepy#ent).

**Comment by AlexZeGamer** [comment]
I used to use and ENT but we now have direct pronote password since our ENT crash in the beginning of the lockdown. I used those.

It also works fine with this type of url :
> It seems like it only works if I put the `?login=true` that is at the end of the url
> (`https://0000000a.index-education.net/pronote/eleve.html?login=true`)
It was surely the problem and I think you sould include it in the docs

**Comment by bain3** [comment]
I am aware that you can get the login page of a pronote that uses ent with this method, but until now it wasn't needed. I'll try and add this to pronotepy asap.

**Comment by bain3** [comment]
I checked how pronotepy will handle an url with the `?login=true` at the end. It seems to work perfectly fine. Did you try it with the login parameter, or just without? If you did, then the issue is something else.

**Comment by AlexZeGamer** [comment]
Yes I tried with the parameter and it worked

**Comment by bain3** [comment]
Ok i misunderstood you then.
